### ISSUE TITLE
Use tcx.sess.check_name to avoid unused attribute lint for #[spriv] attributes

### ISSUE THREAD

**Issue by bjorn3** [EmbarkStudios/rust-gpu#101]
https://doc.rust-lang.org/nightly/nightly-rustc/rustc_session/struct.Session.html#method.check_name

The docs say that tools shouldn't use it, but that was probably written when `#![register_attr]` didn't exist yet.

**Comment by bjorn3** [comment]
In PM @khyperia said this doesn't work as the lint is fired before the codegen backend runs.

**Comment by khyperia** [comment]
We should fix rustc here, littering `#[allow(unused_attributes)]` everywhere is not a long-term solution. So, re-opening this issue. Tasks:

1) Move the rustc lint pass after the codegen backend has ran, or some other solution. (Not sure how happy rustc folks would be with delaying lints until after the potentially very long codegen. Does codegen even run with `cargo check` and friends? We have to solve this somehow, though.)
2) Implement whatever solution in `rust-gpu`.

**Comment by XAMPPRocky** [comment]
I'm pretty sure this is resolved now.
