### ISSUE TITLE
Fix issue with spirv-cross colliding names with builtins

### ISSUE THREAD

**Issue by khyperia** [EmbarkStudios/rust-gpu#102]
Found in https://github.com/EmbarkStudios/rust-gpu/pull/86#issuecomment-714378730

Investigated a bit, turns out spirv-cross uses the `OpName` of functions directly in its output (rude! against spec!), which then can of course collide with builtins and other items. Some options:

- Disable OpName generation when targeting spirv-cross
- Collect builtin names in spirv-cross, and rename things in the compiler when there's a collision
- Make sure OpNames are fully qualified and unique (presumably there might be collisions between two functions named the same in separate crates or something...). Either the `rustc-demangle` crate or `tcx.def_path_debug_str` could help here, as well as `-Zsymbol-mangling-version=v0` to include all generic parameters in the symbol.

**Comment by eddyb** [comment]
Could `OpName` just be the mangled symbol? Even pre-`v0` mangling, there's still a hash which ensures unique symbol names.

Presumably entry points would bypass that but that's more like an implicit `#[no_mangle]` IMO.

**Comment by khyperia** [comment]
Perhaps? `OpName` is specifically for debugging, it has no semantic meaning whatsoever, so it's a little unfortunate if we make it mangled and so much less readable by humans. It's better than no information, though, I guess!

**Comment by hrydgard** [comment]
Have we filed an issue against spirv-cross?

**Comment by khyperia** [comment]
> Have we filed an issue against spirv-cross?

As far as I know, no - at least basing off my fuzzy memory and the fact no spirv-cross issues link to this one :P

Feel free to file one, poke me if you'd like me to instead!

**Comment by hrydgard** [comment]
I think probably you have more context and will be able to write a better issue :) But I can write one if you don't have time.
