### ISSUE TITLE
The example panics with `ERROR_OUT_OF_DATE_KHR` on a window resize.

### ISSUE THREAD

**Issue by expenses** [EmbarkStudios/rust-gpu#103]
Not a huge deal ofc, but it'd make running the example in a tiling wm easier. You just need to rebuild the swap chain upon resize for this.

**Comment by jirislav** [comment]
I've implemented a self mutable `recreate_swap_chain` function as [proposed in Vulcan tutorial](https://vulkan-tutorial.com/Drawing_a_triangle/Swap_chain_recreation), whose definition looks like this:

```rust

    pub fn recreate_swap_chain(
        &mut self,
    ) -> () {
        unsafe {
            self.device.device_wait_idle().unwrap();
            // many lines of copy&paste code for now ..
        }
    }
```

Then I've tried to update the render loop as follows:
```diff
@@ -1003,16 +1231,22 @@ fn main() {
 
         let graphic_pipeline = graphics_pipelines[0];
 
-        base.render_loop(events_loop, move |base| {
-            let (present_index, _) = base
+        base.render_loop(events_loop, move |mut base| {
+            let (present_index, _) = match base
                 .swapchain_loader
                 .acquire_next_image(
                     base.swapchain,
                     std::u64::MAX,
                     base.present_complete_semaphore,
                     vk::Fence::null(),
-                )
-                .unwrap();
+                ) {
+                Ok(res) => res,
+                Err(vk::Result::ERROR_OUT_OF_DATE_KHR) | Err(vk::Result::SUBOPTIMAL_KHR) => {
+                    base.recreate_swap_chain();
+                    return;
+                }
+                Err(err) => panic!("Unkown error: {:?}", err),
+            };
             let clear_values = [
                 vk::ClearValue {
                     color: vk::ClearColorValue {
```

But I get this error and I don't know how to get out of it :/

```
error[E0596]: cannot borrow `*base` as mutable, as it is behind a `&` reference
    --> examples/example-runner/src/main.rs:1245:21
     |
1234 |         base.render_loop(events_loop, move |mut base| {
     |                                                 ---- help: consider changing this to be a mutable reference: `&mut ExampleBase`
...
1245 |                     base.recreate_swap_chain();
     |                     ^^^^ `base` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```

I've also tried to use `ref mut base`, as suggested, with no luck. I guess, that it's impossible to mutate the value when the `render_loop` argument function `F: Fn(&Self) + 'static>` requires a reference? Hence the error that it cannot borrow reference as mutable.

I thought of implementing a `Copy` trait to `ExampleBase`, but that's seems too nasty to me, any thoughts?

**Comment by expenses** [comment]
@jirislav Could you upload your fork for this? I'll try and have a look.

**Comment by jirislav** [comment]
> @jirislav Could you upload your fork for this? I'll try and have a look.

Yup, I've created a draft PR, feel free to check it out. Thank you ;)

**Comment by khyperia** [comment]
I think this was fixed by https://github.com/EmbarkStudios/rust-gpu/pull/299
