### ISSUE TITLE
`num-traits` needs the i128 feature enabled to build with modern Rust versions

### ISSUE THREAD

**Issue by enderger** [EmbarkStudios/rust-gpu#1047]
### Expected Behaviour
The crate should compile by default

### Example & Steps To Reproduce
1. Create a `rust-gpu` shader crate using the exact version of `rustc` needed and `num-traits` 0.15
2. Attempt to compile
3. Read the docs of [num-traits](https://docs.rs/num-traits/latest/num_traits/cast/trait.FromPrimitive.html#method.from_u128) to discover why the error happens

## System Info
- Rustc version: `rustc 1.69.0-nightly (44cfafe2f 2023-03-03)`
- SPIR-V version: `unknown`

 - Rust: rustc 1.69.0-nightly (44cfafe2f 2023-03-03)
 - OS: NixOS Unstable 23.05 (Stoat)
 - GPU: Intel(R) Arc(tm) A770 Graphics (DG2)
 - SPIR-V: unknown

## Backtrace

<details><summary>Backtrace</summary>
<p>

```
cargo build --release
...
   Compiling spirv-tools v0.9.0
error[E0599]: no function or associated item named `from_u128` found for type parameter `
P` in the current scope
   --> /home/enderger/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc_codegen_spirv
-0.7.0/src/abi.rs:867:26
    |
861 |             fn const_int_value<'tcx, P: FromPrimitive>(
    |                                      - function or associated item `from_u128` not 
found for this type parameter
...
867 |                 match P::from_u128(value) {
    |                          ^^^^^^^^^
    |                          |
    |                          function or associated item not found in `P`
    |                          help: there is an associated function with a similar name:
 `from_u8`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `rustc_codegen_spirv` due to previous error
```

</p>
</details>

**Comment by eddyb** [comment]
The error is in `rustc_codegen_spirv` which is *not* code compiled for the GPU, but rather a compiler backend (and 128-bit integers are used in a bunch of places in `rustc`).
How are you managing to influence the compilation of `rustc_codegen_spirv` from your project?
Can you share your `Cargo.toml` + `Cargo.lock`? Or at least gist the output of `cargo tree -e features`.

**Comment by figsoda** [comment]
@enderger If you were using fenix, this should now be fixed

**Comment by eddyb** [comment]
Assuming this was an external bug with `rust-toolchain.toml` being ignored, closing for now.
