### ISSUE TITLE
Rust-gpu in crates.io is misleading

### ISSUE THREAD

**Issue by cybersoulK** [EmbarkStudios/rust-gpu#1063]
as a beginner, i will try to use rust-gpu 0.1 in crates.io, and think it's outdated in crates.io.
We can update the rust-gpu, or provide links and explanation to the different crates (spirv-builder and spirv-std)

**Comment by eddyb** [comment]
> and think it's outdated in `crates.io`

To be clear, there's nothing there, it's just reserved. It might be good to yank it (as long as that keeps the reservation), which would prevent people from accidentally trying to use it (cc @repi).

We may still end up using it, e.g. if this RFC lands, it could become a namespace crate:
* https://github.com/rust-lang/rfcs/pull/3243

**Comment by repi** [comment]
have published an update of it that links to this repo instead, and yanked the versions (good idea!).
