### ISSUE TITLE
Please advise on how to benchmark GPU with Rust-GPU

### ISSUE THREAD

**Issue by jczaja** [EmbarkStudios/rust-gpu#1078]
Hi,

I 'm developing a tool for benchmarking CPU&GPU. For CPU I have some inline assembly kernels doing FMA instructions (vector instruction to perform multiplication and adding) that are executed number of times which is measured and then I can derive FLOPS (floating point operations per second) value. I would like to do the same for GPU.  So to maintain some portability I'm planning to used inline SPIR-V functionality of Rust-GPU.  So I have questions:

1)Is this (inline SPIR-V) good way of measuring FLOPS on GPU? Or maybe you can suggest better way of benchmarking FLOPS for GPU from Rust?
2) I can see compiler is cutting out dead code from my gpu kernel (even when I set in shader create that optimization level should be zero for release profile). How to make compiler not to do any optimizations when producing SPIR-V ?

**Comment by eddyb** [comment]
> How to make compiler not to do any optimizations when producing SPIR-V ?

You do not disable optimizations when benchmarking, as that both adds irrelevant overhead into the mix, and is not actually guaranteed to result in *zero* transformations (i.e. some "optimizations" are actually required to compile *at all*).

In regular Rust you would use e.g. [`std::hint::black_box`](https://doc.rust-lang.org/std/hint/fn.black_box.html) for this, but SPIR-V has no way to express something like that, so drivers will very likely remove your dead FMA instructions *anyway*.

The important insight here is that you don't *actually want* to have "dead FMA instructions", but rather actually have them be dynamically necessary.

This results in the following requirements:
* *all* your inputs must be dynamic (i.e. read from a `#[spirv(push_constant)]` or uniform/storage buffer)
* each execution of an instruction must use *different* inputs (i.e. you need to update some state, and feed it back into itself)
  * you probably need to find an "irreducible" pattern (one that is not just an inefficient way to write some simpler instructions) - perhaps this may work (in a loop):
    ```rust
    d = FMA(c, b, a);
    a = FMA(d, c, b);
    b = FMA(a, d, c);
    c = FMA(b, a, d);
    ```
    (note that I'm feeding each result to one of the the next instructions multiplicative/factor inputs, *not* the additive/term input - this avoids it having any "sequential additions" pattern, though I'm not sure if it has anything else that's similarly bad)
* the final output must be "exported" (i.e. you need to write it to a buffer)

You should probably still use vendor provided tools (i.e. from AMD, Nvidia, etc.) to disassemble the shader and make sure all your FMAs are still there *anyway*.
