### ISSUE TITLE
Using RenderDoc with current spirv-builder design is hard

### ISSUE THREAD

**Issue by termhn** [EmbarkStudios/rust-gpu#108]
Currently, since we rely on an environment variable to actually transmit the compiled spirv, we also rely on cargo to be the environment actually running the executable.  When debugging, renderdoc is very useful but we'd need to actually manually copy-paste the compiled spirv into an env variable within renderdoc's run environment in order for it to work properly.

I think spitting out an intermediate file rather than using environment variables would be preferable here.

**Comment by Jasper-Bekkers** [comment]
Could you explain the problem RenderDoc is having? I used it yesterday on the project and other then having to manually patch out the VariablePointer capability (in the compiler, my RenderDoc version didn't support it) I could debug our shaders as SPIR-V just fine, but maybe I'm missing something?

**Comment by DJMcNab** [comment]
My impression is that the SpirvBuilder does emit a file, specifically into `target/spirv-unknown-unknown/release/[shader_name].spv`

**Comment by termhn** [comment]
> Could you explain the problem RenderDoc is having? I used it yesterday on the project and other then having to manually patch out the VariablePointer capability or the Vulkan memory model (in the compiler, my RenderDoc version didn't support it) I could debug our shaders as SPIR-V just fine, but maybe I'm missing something?

hm, I didn't actually try it because of my mental model of how env!() works but now that I think about it, that's a compile time macro and so it actually is baking the shader into the binary, so it should work perfectly fine. So, nvm, gonna close this :D
