### ISSUE TITLE
Redirect to active community-maintained fork 

### ISSUE THREAD

**Issue by alice-i-cecile** [EmbarkStudios/rust-gpu#1156]
The new repo can be found at https://github.com/Rust-GPU/rust-gpu.

It would be nice to archive this repo and link this in the README.

**Comment by fu5ha** [comment]
Linked prominently in readme. We aren't archiving the repo since we are still using rust-gpu and plan to continue to contribute upstream, so we need a place to house Embark's rust-gpu code.

**Comment by alice-i-cecile** [comment]
Awesome, thanks a ton!
