### ISSUE TITLE
cargo build fails on windows

### ISSUE THREAD

**Issue by khyperia** [EmbarkStudios/rust-gpu#119]
Can't find the symbol `_fltused`. Ugh.

Fix this in CI to have the `cargo build` line not have `-p example-runner` once this is fixed.

**Comment by bjorn3** [comment]
Is it accidentally trying to compile the shader for the host too?

**Comment by khyperia** [comment]
That is intentional. It is part of the project roadmap, a goal of the project is to e.g. be able to debug shaders on the CPU.

**Comment by bjorn3** [comment]
Maybe use `#![cfg_attr(target_arch = "spirv"), no_std]` at https://github.com/EmbarkStudios/rust-gpu/blob/8681464af7e2500f371e5df6a95691cf29ecd16a/spirv-std/src/lib.rs#L1

That will ensure that any linked dylib will have all dependencies required for the target triple.
