### ISSUE TITLE
Investigate adding fast-math functions

### ISSUE THREAD

**Issue by Jasper-Bekkers** [EmbarkStudios/rust-gpu#12]
Relevant: https://github.com/rust-lang/rust/issues/21690

My current thinking around this is that we probably shouldn't even do this.

However, if we do this, I'm kind of partial to having something like `unsafe fn sqrt_approx()` implemented on floats, that one needs to call explicitly within an unsafe block. As discussed in that issue, there are quite a few problems with the existing LLVM backend, it's optimizations etc. Many of which we don't need to care about because we're rolling our own. Having said that, SPIR-V and especially Vulkan have their own set of restrictions around floats: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#spirvenv-precision-operation

**Comment by khyperia** [comment]
This probably isn't on our roadmap any time soon, so closing this until someone has a concrete need for it with opinions and desires we can design the feature around.
