### ISSUE TITLE
Document spirv attributes in dev guide.

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#121]
There are a couple of attributes included with `rust-gpu` but currently we don't have any documentation on their function.

### Example
```rust
#[spirv(entry = "fragment")]
pub fn main_fs(input: Input<Vec4>, mut output: Output<Vec4>) {}
```

**Comment by khyperia** [comment]
I believe this was "fixed" (??) by https://github.com/EmbarkStudios/rust-gpu/pull/145
