### ISSUE TITLE
Rust nightly 2020-10-25 broke build & is not supported

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-gpu#137]
Looks like our CI started failing with the Rust nightly build from today. 
https://github.com/EmbarkStudios/rust-gpu/runs/1305181659

Maybe we should pin to a specific nightly version in `rust-toolchain` now when more people are working with the repo to prevent breakages as it is easier for more to be on different versions @khyperia ?

```
   Compiling rustc_codegen_spirv v0.1.0 (D:\a\rust-gpu\rust-gpu\rustc_codegen_spirv)
error[E0053]: method `add_counter_region` has an incompatible type for trait
   --> rustc_codegen_spirv\src\builder\mod.rs:218:5
    |
218 | /     fn add_counter_region(
219 | |         &mut self,
220 | |         _instance: Instance<'tcx>,
221 | |         _function_source_hash: u64,
...   |
225 | |         todo!()
226 | |     }
    | |_____^ expected `bool`, found `()`
    |
    = note: expected fn pointer `fn(&mut builder::Builder<'a, 'tcx>, rustc_middle::ty::Instance<'_>, _, CounterValueReference, CodeRegion) -> bool`
               found fn pointer `fn(&mut builder::Builder<'a, 'tcx>, rustc_middle::ty::Instance<'_>, _, CounterValueReference, CodeRegion)`
```

**Comment by bjorn3** [comment]
cg_clif has a script that will update `rust-toolchain` for the latest version, does a `cargo clean` and remove all old nightly versions at the same time. It also supports commiting with a commit message stating the new rustc version. It may be useful https://github.com/bjorn3/rustc_codegen_cranelift/blob/8ec977e763baee45dbc6b3efd84e96a7e5dc3f91/scripts/rustup.sh (It uses the local time to select the right rustc version, so it may not work of you are not in Europe)

**Comment by repi** [comment]
Nice thx, that does sound like a good workflow.

**Comment by DJMcNab** [comment]
It might be worth setting up this workspace to use [`xtask`](https://github.com/matklad/cargo-xtask), so that we can reimplement that logic in a more sane way.

**Comment by khyperia** [comment]
> Maybe we should pin to a specific nightly version in rust-toolchain now when more people are working with the repo to prevent breakages as it is easier for more to be on different versions @khyperia ?

For context, we've discussed this a few times in the discord, see for example https://discord.com/channels/750717012564770887/750717499737243679/766257424981688331
