### ISSUE TITLE
Hosting API Documentation

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#143]
Right now we're not publishing on crates.io which means we don't currently get freely hosted documentation from docs.rs. It would be nice if we had the API documentation available. This should be relatively simple to add as another step when building the `rust-gpu` dev guide to make available on GitHub Pages.

**Comment by arirawr** [comment]
Yes, either GitHub pages or Netlify (which we have an account for) would work for this.
