### ISSUE TITLE
Support Vulkan Debug Printf validation layer

### ISSUE THREAD

**Issue by termhn** [EmbarkStudios/rust-gpu#151]
It would be cool to be able to pipe `print!()`, `dbg!()` and friends (or introduce similar gpu-specific versions) through to https://vulkan.lunarg.com/doc/sdk/1.2.148.1/windows/debug_printf.html

**Comment by nipunG314** [comment]
Is anyone currently working on this? If not, I would like to take a stab at it.

**Comment by bjorn3** [comment]
I don't know how easy it would be to make it work with rust-gpu, but would it make sense to use [`defmt`](https://github.com/knurling-rs/defmt) for better performance due to less copying on the gpu side? Or is it expected that the amount of prints is very low.

**Comment by nipunG314** [comment]
The article linked mentions above that, by default, that the shader will return a value to the validation layer every time the debug statement is encountered in the shader code. The article mentions that steps can be taken to prevent this from happening, but doesn't highlight any of them. We'll probably have to look into that.

If we don't limit the number of messages, the performance will be very slow, especially in the fragment shader.

**Comment by termhn** [comment]
> Is anyone currently working on this? If not, I would like to take a stab at it.

Nobody is working on this atm, no. Go for it :)

> The article linked mentions above that, by default, that the shader will return a value to the validation layer every time the debug statement is encountered in the shader code. The article mentions that steps can be taken to prevent this from happening, but doesn't highlight any of them. We'll probably have to look into that.
> 
> If we don't limit the number of messages, the performance will be very slow, especially in the fragment shader.

yeah, perf is always going to be bad if you're printing from a shader though so I wouldn't worry too much about micro perf opts for this path atm.

**Comment by khyperia** [comment]
`format_args!` and related infrastructure (`println!`, etc.) may be difficult to re-use. As far as I understand it, arguments are stored into a [`fmt::ArgumentV1` struct](https://github.com/rust-lang/rust/blob/07e968b640e8ff76fa8be4b48b70ab80ea577800/library/core/src/fmt/mod.rs#L237-L240), which contains a pointer to a `fmt::Opaque`, as well as a function pointer that takes a `fmt::Opaque` pointer, casts it to the right type, and formats it.

This is problematic for multiple reasons:

1) Casting a pointer to an arbitrary type to a pointer to a `fmt::Opaque` is not supported in spir-v (nor GPU hardware) (so no transmute on pointers, etc.)
2) Function pointers are not supported in spir-v (so no vtables too, etc.)
3) Casting the Opaque back to the concrete type is also not supported, for the same reason.

Not sure what ways around this there are, probably can figure out something, but might take a bit of exploration. If you want to do that exploration, go for it! Just might be a lot to do :)

**Comment by khyperia** [comment]
Talked about this with the wonderful @m-ou-se for a bit, and she had some ideas:

- `b"asdf"` compiles to `&[u8; 4]`, a sized array! That we can deal with, perhaps with [`register_constant_pointer`](https://github.com/EmbarkStudios/rust-gpu/blob/706f4cc695a1e0eaf5ad770d4830e0ba2fadf637/rustc_codegen_spirv/src/codegen_cx/mod.rs#L174) to strip away the reference.
- "it should be doable to make a proc macro `gpu_print!("asdf {}", 1.0)` that results in `some_intrinsic(b"asdf %f", 1.0)`"

and the `debug_printf` extension is, well, literally printf, so we'd compile `some_intrinsic` to that instruction.

**Comment by nipunG314** [comment]
I have question about this. I think I'm misunderstanding something.

For the Vulkan backend, at least, wouldn't it be sufficient to add the `OpExtension` and the `OpExtInstImport` instructions and append the `OpExtInst` instruction everytime we want to call debug_printf.

When debug_printf is called, it sends the intended value into a buffer held by the validation layers, which then gets converted to a string and sent to the debugCallbackEXT function (or stdout if it hasn't been defined).

According to the linked document, the module is using the Result<id>s to store references for which value has to be sent to the validation layers. We don't need to specify a pointer on the CPU side for that (or do we? This is the part I'm not sure about).

If we're using the validation layer and debug_printf for this, we don't need to manage the output string's memory (like in the sized array in the previous post). My question is: do we want to depend on the Vulkan validation layer for this feature or make it completely in Rust?

**Comment by khyperia** [comment]
This isn't on our roadmap at all and we don't plan on implementing this, so I'm closing this for now.
