### ISSUE TITLE
OpenGL compatibility

### ISSUE THREAD

**Issue by msiglreith** [EmbarkStudios/rust-gpu#167]
OpenGL supports binary SPIR-V shaders as source since 4.6, mostly feature compatible with Vulkan shader requirements.
Right now `rust-gpu` requires the `Vulkan` memory model which is not support. OpenGL only supports the GLSL450 model.
Would be interesting how deep the implementation relays on it. Quickly tweaking the capabilities and extensions towards GLSL results in a binary which can be passed to OpenGL.

(rather a feature request than a bug)

**Comment by repi** [comment]
Interesting, thanks for filing! 

Do you have any specific use case of OpenGL with SPIRV where Vulkan is not available / appropriate?

**Comment by msiglreith** [comment]
> Do you have any specific use case of OpenGL with SPIRV where Vulkan is not available / appropriate?

No, I mainly use OpenGL for trying out stuff, as it's easier to setup and iterate for me compared to Vulkan. Combining it with `rust-gpu` sounds appealing to me as it might make is even more pleasant in the future!

**Comment by Jasper-Bekkers** [comment]
Keep in mind that in the future some of the features might _require_ the Vulkan Memory Model.

**Comment by khyperia** [comment]
and further context, those features will be disabled on non-Vulkan, the same way kernel-mode ops are disabled on shader-mode today.

**Comment by msiglreith** [comment]
Thanks, works perfectly! 🎉
[Ported](https://github.com/msiglreith/grr-gpu/blob/main/shader/src/lib.rs) a small shader I saw on shadertoy:
![grafik](https://user-images.githubusercontent.com/7253845/97618421-49d5f880-1a1f-11eb-8dd3-3750c7970f2c.png)
