### ISSUE TITLE
standardize example runner windows sizes to 720p

### ISSUE THREAD

**Issue by termhn** [EmbarkStudios/rust-gpu#178]
Currently, all the example runners have different sizes, with the ash runner making a pretty unwieldy full 1080p window. Should standardize them to 720p

**Comment by nolanderc** [comment]
Hi!
I'm new to the project, but looking to start making some contributions. Thought I could start with this issue to get used to the workflow.

720p is a reasonable standard resolution, however, I'm wondering if maybe a fixed-percentage (75% or 67% or so) of the monitor resolution would be better for users with 4K monitors?

**Comment by repi** [comment]
Screen percentage size makes sense for a game or a real app, but for us and these small examples having a fixed size that works everywhere is easier and will work well. These are not real applications just small test examples.
