### ISSUE TITLE
Support additional shader intrinsics

### ISSUE THREAD

**Issue by Jasper-Bekkers** [EmbarkStudios/rust-gpu#197]
Some of these are only available in specific shader stages and should error out in other stages (for example, calculating screenspace derivatives might be unavailable outside pixel shaders). Also some of these may need to add additional capablities (such as SubgropuBallotKHR).

## Generic math functions
 - Already documented in #81
 - Possibly: OpDot & OpOuterProduct

## Bit instructions
 - OpBitFieldInsert
 - OpBitFieldSExtract / OpBitFieldUExtract
 - OpBitReverse
 - OpBitCount

## Fragment shader functions

 - OpDPdx (done)
 - OpDPdy (done)
 - OpFwidth (done)
 - OpDPdxFine (done)
 - OpDPdyFine (done)
 - OpFwidthFine (done)
 - OpDPdxCoarse (done)
 - OpDPdyCoarse (done)
 - OpFwidthCoarse (done)
 - OpKill (we may also want to take a look at OpDemoteToHelperInvocationEXT instead which is probably a nicer alternative depending on platform support; https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/EXT/SPV_EXT_demote_to_helper_invocation.asciidoc and https://github.com/microsoft/DirectXShaderCompiler/issues/2823)

## Compute
 - OpControlBarrier
 - OpMemoryBarrier (see also https://github.com/EmbarkStudios/rust-gpu/pull/216)

### Subgroup instructions
 - Probably all of "3.37.21. Group and Subgroup Instructions" and "3.37.24. Non-Uniform Instructions", but if we want to start with a more limited set the following three are probably fine.
 - OpSubgroupBallotKHR
 - OpSubgroupFirstInvocationKHR
 - OpSubgroupReadInvocationKHR

**Comment by khyperia** [comment]
> Possibly: OpDot & OpOuterProduct

I'm confused. I thought you had the opinion that we should not add vector operation support (like add) because the componentwise operations are good enough - how are these different?

**Comment by Jasper-Bekkers** [comment]
> I'm confused. I thought you had the opinion that we should not add vector operation support (like add) because the componentwise operations are good enough - how are these different?

Yeah that's why I marked them as optional; I think there might be some hw accelerated OpDot's out there but I think they're rare (old desktop parts or mobile gpus).

**Comment by khyperia** [comment]
"Subgroup instructions" sounds like a `good first issue` - relatively straightforward, use `asm!` to implement. Something like this (example for `OpGroupAll`, `Scope = Workgroup`), although I haven't compiled this or checked it at all, just pseudocode:

```rust
unsafe fn group_all_workgroup(x: bool) {
  #[cfg(not(target_arch = "spirv"))]
  panic!()
  #[cfg(target_arch = "spirv")]
  {
    let result;
    asm!(
      "%int = OpTypeInt 32 0",
      "%scope = OpConstant %int 2",
      "{1} = OpGroupAll typeof{0} %scope {0}",
      x, result
    );
    result
  }
}

**Comment by khyperia** [comment]
Moving this to `spirv-std` since with `asm!`, it's mostly (entirely?) a library change

**Comment by khyperia** [comment]
I think the remaining instructions on this issue we don't have a priority for, and so probably shouldn't implement.
