### ISSUE TITLE
List previous Rust on GPU initatives and related projects

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-gpu#20]
We talked in the meeting today (#15) that it would be good to list out all previous related Rust GPU initiatives and projects in the README, and maybe a bit how they relate or differ from the approach(es) we are taking here.

Could put them under a "Previous Work and Related Projects" section

- 2013 - Experimental Rust PTX compute backend on Nvidia GPU
  - @pcwalton do you have any more links or info about it? 
- 2018 - [Accel](https://github.com/termoshtt/accel)
- 2019 - RLSL by @MaikKlein. This we do mention in the README, but can compare more

Likely more?

**Comment by msiglreith** [comment]
I have a few more for the archives:
- 2016: [`glassfull`](https://github.com/kmcallister/glassful) syntax plugin/macro to translate to GLSL
- 2017: [`inspirv`](https://github.com/msiglreith/inspirv-rust) my MIR -> SPIR-V compiler experiments

**Comment by ColeSeverson** [comment]
Is this change still wanted/needed? I would be happy to take it up as I familiarize myself with the project,

**Comment by repi** [comment]
sure! Imagining a pretty brief README section with like a one-liner for each related project in chronological order, or something like that

**Comment by ColeSeverson** [comment]
Created a PR for this change: https://github.com/EmbarkStudios/rust-gpu/pull/794
