### ISSUE TITLE
Constant Runtime Array Value when compiling panic_abort

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#211]
https://github.com/rust-lang/rust/blob/master/library/panic_abort/src/lib.rs

The only runtime array value in that crate is inlined below but I don't think that's the cause since it's only used in a `emscripten` environment.

```rust
    // Similar to above, this corresponds to the `eh_catch_typeinfo` lang item
    // that's only used on Emscripten currently.
    //
    // Since panics don't generate exceptions and foreign exceptions are
    // currently UB with -C panic=abort (although this may be subject to
    // change), any catch_unwind calls will never use this typeinfo.
    #[rustc_std_internal_symbol]
    #[allow(non_upper_case_globals)]
    #[cfg(target_os = "emscripten")]
    static rust_eh_catch_typeinfo: [usize; 2] = [0; 2];
```

```
error: constant runtime array value

error: aborting due to previous error

error: could not compile `panic_abort`
```

**Comment by bjorn3** [comment]
`SpirvType::RuntimeArray` is used for DSTs with `FieldsShape::Array` like `[T]`. `FieldsShape::Array` is used for `[T]`, `[T; N]` (not a DST), `str`, and vector types (not a DST).

https://github.com/rust-lang/rust/blob/b5c9e2448c9ace53ad5c11585803894651b18b0a/compiler/rustc_middle/src/ty/layout.rs

I don't see any usage of a type that could use `RuntimeArray` in `panic_abort`. Can you get a span or at least function name?

**Comment by khyperia** [comment]
I don't think compiling `panic_abort` is a priority right now, so closing this until we hit the same error in code that we actually do care about. There's just too many compiler tasks to try to fix all of them.
