### ISSUE TITLE
Meeting 2020-11-05

### ISSUE THREAD

**Issue by arirawr** [EmbarkStudios/rust-gpu#213]
Previous meeting: #144 

Time: 17:00 CET
Where: #rust-gpu voice channel on Ark Discord.

Agenda
(please edit/add)
- small intros
- @khyperia project update
- recent contributions, things in flight
- 0.2? 😮 
    - also, release process/frequency/publishing
- build system bikeshedding 😛

**Comment by repi** [comment]
# Meeting notes

Participants

- @repi
- @khyperia
- @VZout
- @Jasper-Bekkers
- @Jake-Shadle
- @arirawr
- @XAMPPRocky
- @termhn
- Additional guests from Discord!
    - @nolanderc
    - @msiglreith

## Minutes

### What are we working on

- @termhn Converting Ark shaders #36
  - Been going pretty well so far. 
  - Started with mesh shader, if it works then most of our features that we need will be in place for our other shaders also
  - Will make list of what compiler features we need
  - Also wrote up an issue about color conventions, not directly related
  - Can't do "buffer blocks", multiple uniforms in one buffer
    - @khyperia May be very easy to hack in support for it

- @Jasper-Bekkers Doing RFC on inputs/outputs on shader stages (link?)

- @MarijnS95 working on Android, works fine! #190

- @khyperia Build systems, compiler fixes, bunch of stuff in flight

- @VZout continuing working on structurizer 
    - Bug: two if statements in a single function
    - Switch statements is not supported yet
    - May get some help on the irreducible -> reducible spirv paths
    - Fixing bugs right now
    - @nolanderc asked if can help, probably not at this point

- @repi Did an experiment with hot-reloading of shaders in example
  - Works really well and is surprisingly nice even in our small examples
  - Still embeds the initial shader in the executable, but then uses `cargo watch` and monitors the target folder to reload the `.spv` files
  - Will do draft PR

- @XAMPPRocky Build system.
    - How things are built with rustc
    - Also building our own sysroot. nice cargo-sysroot crate
    - New spirv json file? @khyperia: shouldn't be needed
    - Don't need spirv-builder. hopefully

### rust-gpu 0.2?

- Do a proper next release with release notes as mini blog post and new screenshot(s)

- Target: Mid December

- What to include/require, @khyperia: "everything gray requests for parts" (to bring up the Ark shaders)

- Publish our crates on crates.io? Yes, to be able to build without git dependency

- Maybe compute shaders if it is in
    - @nolanderc wants it also
    - @khyperia: GL/Vulkan or OpenCL, (answer: GL/Vulkan)

- spirv-std. yes. writing shaders without 
- maybe not spirv-builder? May have different build system

- backend-cranelift crates.io is a rustc binary front-end

- Get some more example shaders
   - once textures are in @khyperia will re-write her raytracer in.
   - @VZout will add his shaders
   - Potentially could include some of our Ark shaders as well, nothing too special but good test cases
   
- Want match/switch statements

- Generally positive to to people to have these versioned releases, get some roadmap
    - Provides some timelines
    - Good way to communicate out to the community and engage
    - Writing good release notes, small mini-blog and share on r/rust and twitter and such

### Build system discussions

- Or really: how do you use Rust GPU?

- Right now done in build.rs that builds the compiler and the shader crate through `spirv-builder`

- Has a bunch of problems:
    - The core library is difficult to use
    - 2 spriv crates built at the same time locks it up, not great
    - possible:
        - custom sysroot
        - custom rust backend

- @repi: impossible to solve all 3 build phases in cargo today

- Examples of other ways of building
    - Rust: x.py
    - cargo make ("cross-platform" bash scripts in a toml)
    - Ark bark-like (Rust program instead of shell/python script that builds everything)

- Also want to run tests and check links.

### Other

- @Jake-Shadle: Move spirv-tools to separate repo?
    - Decision: yes let's move it to simplify things in this repo
