### ISSUE TITLE
Are you aware of SPIRV-LLVM-Translator?

### ISSUE THREAD

**Issue by Logarithmus** [EmbarkStudios/rust-gpu#217]
Hello. I'm very excited with this project. Hope it goes well. Have you considered using SPIR-V LLVM translator instead of writing your own rustc codegen backend from scratch? https://github.com/KhronosGroup/SPIRV-LLVM-Translator
**P. S.** I didn't test it personally, possibly it's immature and unstable yet. Anyway, IMHO it would be easier to use existing code instead of writing from scratch.
**P. P. S.** Or maybe your goal is to avoid depending on LLVM/C++/C at all?

**Comment by khyperia** [comment]
SPIRV-LLVM-Translator is explicitly targeting the use case of kernel-mode spir-v, not shaders. The primary goals of this project are to enable shaders to be written in rust, and so SPIRV-LLVM-Translator does not fit our needs. As far as I can tell (and from my own experience trying to support both), there is an enormous amount of work to be done in SPIRV-LLVM-Translator to get shaders to work and I don't expect it to be done any time soon. (To be honest, in my opinion, kernel mode spir-v and shader mode probably should have been separate specs - they are significantly different)

**Comment by Logarithmus** [comment]
Thank you for the explanation. To be clear, I'm not familiar with neither kernel-mode nor shader SPIR-V. I'll investigate this topic later in my spare time.
P. S. Is there any way to donate for the project?

10 ноября 2020 г. 10:34:12 GMT+03:00, Ashley Hauck <notifications@github.com> пишет:
>SPIRV-LLVM-Translator is explicitly targeting the use case of
>kernel-mode spir-v, not shaders. The primary goals of this project are
>to enable shaders to be written in rust, and so SPIRV-LLVM-Translator
>does not fit our needs. As far as I can tell (and from my own
>experience trying to support both), there is an enormous amount of work
>to be done in SPIRV-LLVM-Translator to get shaders to work and I don't
>expect it to be done any time soon. (To be honest, in my opinion,
>kernel mode spir-v and shader mode probably should have been separate
>specs - they are significantly different)

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by repi** [comment]
> P. S. Is there any way to donate for the project?

Thanks for the offer! But no that is not needed. We ([Embark](https://embark.games)) are a corporation and have the funding we need to drive this project.

**Comment by khyperia** [comment]
Thanks for the pointer! It certainly would be nice to not duplicate work, but yeah, we unfortunately need to.
