### ISSUE TITLE
Better error message when SPIR-V version mismatch

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#225]
Currently `rust-gpu` ICE's if you accidentally use a module with the wrong SPIR-V version. It would be better to provide a nice compiler error instead.
 
```
 thread 'rustc' panicked at 'assertion failed: `(left == right)`
    left: `(1, 0)`,
   right: `(1, 3)`', crates/rustc_codegen_spirv/src/linker/mod.rs:102:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

  error: internal compiler error: unexpected panic

  note: the compiler unexpectedly panicked. this is a bug.

  note: we would appreciate a bug report: https://github.com/EmbarkStudios/rust-gpu/issues/new

  note: rustc 1.49.0-nightly (25f6938da 2020-11-09) running on x86_64-apple-darwin
```

https://github.com/EmbarkStudios/rust-gpu/blob/9c8cec36396a1f328c8582da488d469963982590/crates/rustc_codegen_spirv/src/linker/mod.rs#L102

**Comment by khyperia** [comment]
I'm honestly really curious how you hit this, because there's probably some further bug beyond that (maybe core doesn't rebuild when you change feature flags?), but anyway, submitted PR for just the ICE
