### ISSUE TITLE
Ark shader blockers

### ISSUE THREAD

**Issue by termhn** [EmbarkStudios/rust-gpu#233]
- [x] - https://github.com/EmbarkStudios/rust-gpu/issues/204 (implemented by https://github.com/EmbarkStudios/rust-gpu/pull/276)
- [x] - https://github.com/EmbarkStudios/rust-gpu/issues/192 (fixed by https://github.com/EmbarkStudios/rust-gpu/pull/268)
- [x] - https://github.com/EmbarkStudios/rust-gpu/issues/232
- [x] - #314 

Part of #36

**Comment by Jasper-Bekkers** [comment]
1. Running runners with release mode not working is a blocker as well, ends up in infinite loop
2. Subchecked is a problem in weird cases which is fucked for flags. #274
3. Bindless arrays are seen as runtime arrays? 
```glsl
layout(set = 0, binding = 1) readonly buffer InstanceDataBuffer {
    InstanceDataEntry instance_data[];
};
```
4. Missing nointerpolation attribute. (Needed for the flags on the mesh shader)
5. Hacked in multiview capability would be nice? (Only needed for VR - but easy to add)

**Comment by khyperia** [comment]
- `#[spirv(block)]`, hack fix for https://github.com/EmbarkStudios/rust-gpu/issues/232
- implement strings->panics

**Comment by termhn** [comment]
@khyperia added #314 to this because I think it's blocking for https://github.com/EmbarkStudios/ark/pull/2756 but not sure if that's actually true

**Comment by Jasper-Bekkers** [comment]
I think we can close this now that most Ark shaders have migrated to rust-gpu.
