### ISSUE TITLE
sky shader example has validation eror

### ISSUE THREAD

**Issue by termhn** [EmbarkStudios/rust-gpu#247]
Related to #232, push constants when used in a "block" fashion as they are in the sky shader need a Block decoration in spir-v, I guess https://github.com/EmbarkStudios/rust-gpu/issues/232

though it does still work for me, at least on nvidia

**Comment by termhn** [comment]
![image](https://user-images.githubusercontent.com/887711/99454886-45955080-28e4-11eb-8fff-1b10bfacc30c.png)

**Comment by VZout** [comment]
The dev guide example for uniforms has the same error. And you will likely run into this as well when running ark if you enable validation.

**Comment by eddyb** [comment]
SwiftShader uses SPIRV-Tools and that also fails (see https://github.com/EmbarkStudios/rust-gpu/issues/136#issuecomment-732047047) with:
```
SPIR-V ERROR: 0:0 PushConstant id '8' is missing Block decoration.
From Vulkan spec, section 14.5.1:
Such variables must be identified with a Block decoration
  %shared__ShaderConstants = OpTypeStruct %uint %uint %float
```

**Comment by eddyb** [comment]
Looks like this is easy to reproduce with:
```sh
spirv-val --target-env vulkan1.0 target/spirv-unknown-unknown/release/sky_shader.spv
```
