### ISSUE TITLE
Ash runner fails on macOS

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#251]
```
error: could not find native static library `MoltenVK`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `ash-molten`

To learn more, run the command again with --verbose.
```

### System Info

 - Rust: `rustc 1.49.0-nightly (9722952f0 2020-11-12)`
 - OS: macOS 11.0.1

**Comment by repi** [comment]
That is odd. though it should also now use the new `pre-built` feature so it doesn't have to rebuild MoltenVK from scratch all the time, that is what we use in Ark. But building without it should also work

**Comment by XAMPPRocky** [comment]
> That is odd. though it should also now use the new pre-built feature

That fixes it, I'll make a PR.
