### ISSUE TITLE
Meeting 2020-11-19

### ISSUE THREAD

**Issue by khyperia** [EmbarkStudios/rust-gpu#260]
Previous meeting: #227 

Time: 17:00 CET
Where: #rust-gpu voice channel on Ark Discord.

Agenda (please add)
- Who takes notes?
- Welcome @eddyb for realsies this time
- Status/standup - what are you working on? what are you blocked on? (less than a minute per person)
- How is it going with the porting of the Ark shaders? Can we further focus and accelerate that so we it in and try some shaders as soon as possible in Ark for real? and gradually get more and more working, not that many weeks left
- Rust GPU v0.2 mid December, the Ark shaders is still the top priority I think but if we do get that more done targeting a 0.2 release just before holidays, as we talked about in the last meeting, would be great if possible. Both to get some closure in this current push but also as likely a bunch in the community will want to play with Rust GPU with the new features during the holidays :slightly_smiling_face: But if it is too tight and too much work with the Ark shaders perfectly fine to do the release after holidays also

**Comment by XAMPPRocky** [comment]
# Notes

- Ashley + Gray to setup meeting with Jasper and/or Henrik to discus what features in the Ark shaders are actually needed.

### Project Updates

- @khyperia 
    - Working on intercepting libm calls

- @termhn 
    - Updated Glam
    - Getting Macaw Running
        - Probably waiting on libm functionality.

- @eddyb 
    - Getting rust-gpu building with NixOS
    - Trying building rust-gpu in rust repo
    - Working on mangling in names.

- @XAMPPRocky 
    - Still working on build system
    - Works on my machine, problems passing CI.
    - One issue is a weird path resolution bug on Windows.
    - Another is clippy warning about code in libcore.

### Discussion

- @XAMPPRocky
    - We should add some guidelines around issue and pull request triage.

- @khyperia 
    - We should also talk about #249


- Let's set aside time in the next meeting to review it, and regularly discuss MCPs at the weekly meeting.
