### ISSUE TITLE
no method named `atan2` found for type `f32` in the current scope

### ISSUE THREAD

**Issue by krupitskas** [EmbarkStudios/rust-gpu#272]
### Expected Behaviour
Expect to have atan2 function in such code:
```
let l = 0.32f32;
let b = 0.33f32;
let a = l.atan2(b);
```
### Example & Steps To Reproduce
```
let l = 0.32f32;
let b = 0.33f32;
let a = l.atan2(b);
```
```
error[E0599]: no method named `atan2` found for type `f32` in the current scope
    --> shaders\simplest-shader\src\lib.rs:43:15
     |
  43 |     let a = l.atan2(b);
     |               ^^^^^ method not found in `f32`
```

## System Info

 - Rust: [rustc 1.50.0-nightly (98d66340d 2020-11-14)]
 - OS: [Windows 10 19042.662]
 - GPU: [1060 6gb]
 - SPIR-V: [SPIRV-Tools v2020.4 v2020.4]

**Comment by DJMcNab** [comment]
Have you tried:
```rust
use spirv_std::num_traits::float::Float;
```
?

**Comment by krupitskas** [comment]
In the example it was under 
```
#[cfg(target_arch = "spirv")]
```
so it didn't count, because I build for windows platform. Removed this config and it did worked, thanks!
