### ISSUE TITLE
CI should disallow stale Cargo.lock.

### ISSUE THREAD

**Issue by eddyb** [EmbarkStudios/rust-gpu#303]
E.g. #301 changed a dependency but didn't include the `Cargo.lock` change.

This should be easy to fix by just adding `--locked` to the CI `cargo` commands, which will error if `Cargo.lock` isn't up to date.

**Comment by XAMPPRocky** [comment]
Should we just remove it altogether? I don't know if it's particularly valuable here, especially when this is ostensibly a dynamic *library*, as opposed to a binary that people are installing and running on their own.
