### ISSUE TITLE
Compiling with SPIRV-LLVM-Translator

### ISSUE THREAD

**Issue by jarble** [EmbarkStudios/rust-gpu#306]
Is rust-gpu able to compile Rust to GLSL using [SPIRV-LLVM-Translator](https://github.com/KhronosGroup/SPIRV-LLVM-Translator)?

It seems that it would be possible to do this fairly easily, following these steps:
* compile Rust to LLVM IR using `rustc`,
* compile LLVM IR to SPIRV using [SPIRV-LLVM-Translator](https://github.com/KhronosGroup/SPIRV-LLVM-Translator), and then
* compile SPIRV to GLSL using [SPIRV-Cross](SPIRV-Cross).

**Comment by termhn** [comment]
Since we're implementing our own spir-v codegen directly, going thru spirv-llvm-translator is extraneous. You could just convert our generated spirv to glsl using spirv-cross directly.

**Comment by khyperia** [comment]
The `SPIRV-LLVM-Translator` question was already answered in https://github.com/EmbarkStudios/rust-gpu/issues/217, tl;dr `SPIRV-LLVM-Translator` does not support shaders, which is why we wrote our own rustc backend instead of using the LLVM backend.
