### ISSUE TITLE
Support Flat decoration on shader Input/Outputs

### ISSUE THREAD

**Issue by termhn** [EmbarkStudios/rust-gpu#314]
Ideally, we want to be able to do something like
```rs
fn main_vs(
    #[spirv(flat) mut some_output: Output<Blah>
)

fn main_fs(
    #[spirv(flat) some_input: Input<Blah>
)
```
which would apply the Flat decoration and therefore disable interpolation.

**Comment by khyperia** [comment]
While I'm implementing this, is there any other decorations that we want to support?

The spir-v spec list is here https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#Decoration

Decorations that can be applied to input/outputs are: NoPerspective, Flat, Patch, Centroid, Sample, Component. Those don't look toooo useful/relevant right now, and can probably wait until the binding RFC to be implemented - only NoPerspective seems like something we might potentially use.
