### ISSUE TITLE
Slices: Allow more PassModes in entry args

### ISSUE THREAD

**Issue by charles-r-earp** [EmbarkStudios/rust-gpu#316]
Currently you cannot have a slice in an entry argument, due to this restriction (since slices are passed as a scalar pair). If not, then slices will have to be converted to a pointer? 
   
     // rustc_codegen_spirv/src/codegen_cx/entry.rs

    for (abi, arg) in fn_abi.args.iter().zip(body.params) {
            if let PassMode::Direct(_) = abi.mode {    /* <--- allow PassMode::Pair() */ 
            } else {
                self.tcx.sess.span_err(
                    arg.span,
                    &format!("PassMode {:?} invalid for entry point parameter", abi.mode),
                )
            }
        }

There is OpArrayLength for getting the length of the array, passing it this way doesn't work.

**Comment by khyperia** [comment]
Thanks for the issue! Yes, PassMode::Pair is currently not allowed, and #300 will need to be implemented to allow `!Sized` arguments in parameter lists. There is no quick hack fix to allow PassMode::Pair in the current system, but we've already designed how it will work in the new binding model RFC, and is part of other issues currently open, so I'm closing this.
