### ISSUE TITLE
Meeting 2020-12-10

### ISSUE THREAD

**Issue by Jasper-Bekkers** [EmbarkStudios/rust-gpu#334]
### Where & When
- `#rust-gpu` on the [Embark Discord](https://discord.gg/8TW9nfF).
- Time: 17:00 CET
- [Previous Meeting](https://github.com/EmbarkStudios/rust-gpu/issues/262)

### Agenda

- Project updates
- [Review & discuss any open MCPs](https://github.com/EmbarkStudios/rust-gpu/labels/mcp%3A%20proposed)

Feel free to propose additional items in this thread.

**Comment by Jasper-Bekkers** [comment]
- Status of name mangling bug on macOS?
	- :: -> _
	- We need to file issue on spirv-cross to get better entrypoint names
 - Broader question of how to ci?
	 - Swiftshader should work, to do headless ci
	 - GH action to do mac tests
 	 - Amd / Nv testing coverage
 - Do we publish ark shaders on crates.io?
 - Automatic testing for lysol's shader playground shaders?
 - Early q1 mini brainstorm
	- Proper rendering pipeline in ark
	- Rendergraph
	- Scalarizer checker formalized work
	- How to do live shader editing, could be interesting to do an example there ? (`cargo watch`)
	- Could be open to integrate rust-gpu into bevy
	- Create "post your screenshots" issue in our repo
	- Find out which projects want to use it but don't yet and for what 
	
 - Looks like some people missed our 0.2 release
	- Add tag line?
	- Find a good place to announce it

**Comment by repi** [comment]
> Status of name mangling bug on macOS?
> We need to file issue on spirv-cross to get better entrypoint names

@Jasper-Bekkers @VZout did you file an issue on it?

**Comment by VZout** [comment]
Yep: https://github.com/KhronosGroup/SPIRV-Cross/issues/1571
