### ISSUE TITLE
Vector types

### ISSUE THREAD

**Issue by khyperia** [EmbarkStudios/rust-gpu#34]
spir-v has vector types that are dramatically useful on e.g. nvidia hardware for optimizing loads/stores. At first, let's just directly expose vector types, instead of trying to do things like auto-vectorization.

1) Rustc already has the notion of vector types, and we directly translate them to spir-v vector types. We need to investigate under what conditions rustc emits vector types, and if we can re-use the same framework. https://github.com/EmbarkStudios/rust-gpu/blob/9697c227401ffdb02f935ddf860060d6f9978700/rustc_codegen_spirv/src/abi.rs#L332-L339
2) If we cannot re-use the same framework, [create an attribute](https://github.com/EmbarkStudios/rust-gpu/blob/9697c227401ffdb02f935ddf860060d6f9978700/rustc_codegen_spirv/src/symbols.rs#L97) to specify a type is a builtin vector, recognize the attribute in `abi.rs` ([example for storage classes](https://github.com/EmbarkStudios/rust-gpu/blob/9697c227401ffdb02f935ddf860060d6f9978700/rustc_codegen_spirv/src/abi.rs#L547)), and emit a vector type. Perhaps do a mix of the two, e.g. if rust supports f32x2 and f32x4, but not f32x3, then we need to define our own f32x3.
3) Investigate the spec: is emitting a spir-v "OpTypeVector" enough, or are there additional decorations/etc. we need to apply to get it to be a proper "vector type"? https://github.com/EmbarkStudios/rust-gpu/blob/9697c227401ffdb02f935ddf860060d6f9978700/rustc_codegen_spirv/src/spirv_type.rs#L166
4) Implement the above in `spirv-std`, adding things like swizzling ops and other shenanigans (can come later).

This seems like a good not-quite-first-but-kinda-first task for someone other than me to do. Step 2 is a little involved and will likely need some mentorship - `abi.rs` is hecking *wild* - but getting more people who know how `abi.rs` works would be really really good.

**Comment by nipunG314** [comment]
Hi, I would be interested with working on this.

From what I understand in this thread, the first thing to do would be to write the operators and impls for f32x4 using macros?

**Comment by khyperia** [comment]
Awesome!

This issue is a bit out of date, though: https://github.com/EmbarkStudios/rust-gpu/pull/71 added quite a few vector items. However, it wasn't very cleanly or thoroughly implemented, and needs significant work. Some tasks remaining are:

1) vec4 and f32x4 are duplicated right now. One of them needs to be removed. Discussing which naming scheme to go with in discord would be nice, if you're able to join there! 
2) A lot of cruft from glam was copied over, this needs to be fixed (e.g. `reciprocal`), and many weird comments.
3) There's a lot of duplication: it'd be nice if we could deduplicate with macros or somesuch.
4) The clippy `use_self` lint is disabled on `spirv-std`, primarily due to violations in the vector code, it'd be good to fix those.
5) Tests are disabled on spirv-std right now, either remove the tests or enable them.

**Comment by nipunG314** [comment]
Sure. I'll ping you on #rust-gpu on Discord.

**Comment by khyperia** [comment]
With glam and whatnot in, this is pretty much resolved.
