### ISSUE TITLE
Document MoltenVK version requirements.

### ISSUE THREAD

**Issue by eddyb** [EmbarkStudios/rust-gpu#349]
As per https://github.com/KhronosGroup/SPIRV-Cross/pull/1450#issuecomment-746610707, one of the bugs that was hit with MoltenVK so far, should be fixed since MoltenVK v1.1.0 (tho we're still waiting on confirmation).

Also, looking at https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.1.0, it starts off with:
> ### Release for Vulkan 1.1 Support and Vulkan SDK 1.2.154
> * Add support for Vulkan 1.1, including: 

So I'm pretty sure, given that we state Vulkan 1.1+ is required, that we should also say MoltenVK v1.1.0+ is required.

**Comment by eddyb** [comment]
See the edits to https://github.com/KhronosGroup/SPIRV-Cross/pull/1450#issuecomment-746610707 - I sadly was wrong and we still need to deal with the bugs, and they'll only be fixed in a future version.

**Comment by eddyb** [comment]
It ended up being reportedby @VZout as https://github.com/KhronosGroup/SPIRV-Cross/issues/1571, and fixed by https://github.com/KhronosGroup/SPIRV-Cross/pull/1576.
This is included in MoltenVK  v1.1.2 (released a couple days ago), so that's what we should recommend.

**Comment by VZout** [comment]
For completeness: Also this one https://github.com/KhronosGroup/MoltenVK/pull/1204 is required for multiple entry points.
