### ISSUE TITLE
Use cdylib instead of dylib

### ISSUE THREAD

**Issue by bjorn3** [EmbarkStudios/rust-gpu#367]
Why are you using `dylib` as crate type actually? That is only for when you want to use it as a rust dependency. It includes the full crate metadata, dynamically links against libstd and exports all symbols. Even those not usable when not used as a rust dependency but as C dependency.

_Originally posted by @bjorn3 in https://github.com/rust-lang/rfcs/issues/3028#issuecomment-756167656_

**Comment by bjorn3** [comment]
> That is only for when you want to use it as a rust dependency.

I believe this is the main reason, so that you could have a single crate be used as Rust crate on the CPU, and as a GPU shader when compiled with `spirv-unknown-unknown`. This was already in place when I joined the project however, so I’m not aware if there’s further reasoning beyond that. Feel free to file an issue (or I will later) on the repo and we can discuss that more.

_Originally posted by @XAMPPRocky in https://github.com/rust-lang/rfcs/issues/3028#issuecomment-756241629_

**Comment by bjorn3** [comment]
It is possible to define multiple crate types at once. If any is marked as unsupported for the current target, cargo will ignore it, albeit with a warning.

**Comment by khyperia** [comment]
AFAIK `cdylib` has restrictions on what can be exported, or maybe strips rust-specific symbols, or something like that. I don't fully remember, but I remember having problems with `cdylib` (and also `cdylib` makes much less sense, there's nothing C related about compiling to a SPIR-V blob). I don't think interoperability with CPU code was a factor when deciding to use `dylib` (I imagine using `rlib` as a second option would make more sense when a crate is being used on the CPU as well).

> dynamically links against libstd and exports all symbols

In our case, no, our backend does none of that - it spits out a SPIR-V blob, `dylib` is just a hack to get the compiler set up to give the backend enough information for it to take over and do whatever it wants.

**Comment by khyperia** [comment]
Just checked, using `cdylib` doesn't export rust-style functions to the backend, they're all stripped - only FFI-exposed functions are sent to the backend. We rely on Rust features disallowed by FFI-exposed functions (not to mention the user experience of the extra annoyance and hassle caused by the extra export syntax), so we can't use cdylib.
