### ISSUE TITLE
Unused invalid code is accepted

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#368]
Currently unused code that is invalid on `spirv-unknown-unknown` will be accepted if it isn't being used in the code. This is pretty surprising behaviour as it can give you the false impression that we have features and support for features in the language. that we currently don't. For example we currently don't support options (see #234) but as shown below depending on whether the function is pub or not, you'll see an error. Is there a way to elevate some of the validation so that is checked against unused code?

```rust
// Compiles
fn foo () -> Option<u8> { Some(5u8) }
// Errors
pub fn foo () -> Option<u8> { Some(5u8) }
```

**Comment by khyperia** [comment]
I don't think there's an easy way to fix this, and I don't think we're going to ever get around to doing it.
