### ISSUE TITLE
Support Slice Literals

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#378]
Currently you cannot have a static slice literal in your code such as `&[]` or `&[1,2 3, 4]`.

### Error
```
      --> /Users/cargo/git/checkouts/rspirv-50a5048e4e24b3a2/7111e6c/spirv/autogen_spirv.rs:2887:48
       |
  2887 |             GroupOperation::ClusteredReduce => &[Capability::GroupNonUniformClustered],
       |                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       |
       = note: from: *{Function} [u32; 1]
       = note: to: *{Function} [u32]
```

**Comment by khyperia** [comment]
Statically sized slice literals work fine, this passes:

```rust
#[test]
fn slice_constant() {
    val(r#"
#[allow(unused_attributes)]
#[spirv(fragment)]
pub fn main() {
    let x: &[u32; 4] = &[1, 2, 3, 4];
}
"#);
}
```

Unsized slice literals will never be supported, SPIR-V does not support creating OpTypeRuntimeArray values.

(Please let me know how you were compiling rspirv with rust-gpu if it was not intentional, because that's really strange)

**Comment by XAMPPRocky** [comment]
> (Please let me know how you were compiling rspirv with rust-gpu if it was not intentional, because that's really strange)

It was intentional. I was trying to see if we could have `spirv_headers` work in `spirv-std` to save having to redefine stuff.
