### ISSUE TITLE
Add arch module

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#384]
# Proposal

In the spirit of previous discussions of wanting to increase the capabilities of `rust-gpu` while also allowing more iteration to happen in crates outside of the main repo, I'd like to propose adding `arch` module to `spirv-std`, in which there is only single purpose unsafe functions that map to a single instruction in SPIR-V. This would allow more people to use features we currently don't support at any higher level sooner without having to write inline assembly themselves, while also giving us the time to design those abstractions without needing to rush them to provide any level of support in `rust-gpu`.

**Comment by repi** [comment]
Really like this proposal and idea and to enable more devs to directly access low-level "unsafe" intrinsics and functionality to experiment with what to build on top, and to help drive what higher-level ways we should expose functionality in our Rust GPU "std"

**Comment by XAMPPRocky** [comment]
Yeah, based on the discussion in the previous meeting, we're generally in favour of this so I'm going to mark this as accepted, and close this issue. I'll make an initial PR adding some basic instructions and the rest can be tracked through #383
