### ISSUE TITLE
spir-v integration into x86-64 binary, with compiler support for generics

### ISSUE THREAD

**Issue by jon-chuang** [EmbarkStudios/rust-gpu#387]
I wonder if it is not so far fetched to aim for a pathway, lets say a target called spirv-x86, where a well-defined interface, similar to FFI, is created. This is all standard and can be achieved by 3rd party libraries incorporating rust-gpu up to this point, similar to rust-ptx interface libraries.

However, what would be gained in aiming for compiler-level support, is the allowing of specialisation of generics to kernels/shaders. For instance, we could have some `trait RenderBackground` lets say, which is parametrised in a way that the kernels/shaders, are different spirv code entirely. 

I can't give good examples since I work on cryptography rather than graphics, but I hope you can think of some good examples in your domain (in our use case, we want kernels specialise to different elliptic curves that have different bits and equations etc). However, we can then define a generic function `fn run_kernel` that can be compiled with respect to the specific instantiation of the trait.

so we have say
```
impl<P: Parameters> MyTrait for somestruct<P> {
    fn some_fn(..) {
        P::ParamA * ..
    }
    ...
    #[spirv_kernel]
    fn run_kernel(..) {
        MyTrait::some_fn(..);
        MyTrait::other_fn(..);
    }
}
```
So we are instantiating individual kernels with respect to the generic type parameter P, with some automatic rust-side FFI for invoking the `run_kernel` fn.

If you think about it, the alternative is exceedingly ugly, and involves instantiating and compiling kernels for each of the parameters `P` as they are instantiated. Then, one needs to further think about organising these compiled kernels on disk and invoking them for each of the `run_kernel` fns. So it's a huge mess that can be avoided by such an integrated approach. 

I am not sure how relevant it is to embark's use case specifically, but I suppose if one is writing a game engine in rust, then one would presumably want direct integration of CPU and GPU code, especially in a coprocessing setting, and also the ability to instantiate kernels generically for concrete parameters that cannot be captured in generic gpu code. 

(I suppose one example I could think of is the use of metaprogramming to define matmul kernels (Nvidia's CUTLASS), and now maybe this is possible with const-generics which is dropping in rustc stable 1.51).

**Comment by XAMPPRocky** [comment]
Thank you for your issue! I'm not sure I understand what you want to achieve, you can already build and share Rust code between the CPU and GPU.

```rust
fn available_on_cpu_and_gpu() -> u8 {
  5
}

#[cfg(target_arch="spirv")]
fn available_on_gpu_only() -> u8 {
  5
}
#[cfg(not(target_arch="spirv"))]
fn available_on_cpu_only() -> u8 {
  5
}
```

**Comment by jon-chuang** [comment]
@XAMPPRocky Hmm, but can you create kernels parametrised by a generic type?

For instance, 
```
fn mac<I: Integer>(x: I, y: I, c: I) {
    x * y + c
}
```
And then automatically call this as a kernel in another generic context like 
```
impl<I: Integer> trait for MyStruct<I> {
    fn invoke_kernel(x: &[I], y: &[I], c: &[I]) { 
        gpu::launch!(mac::<I>, x, y c);
    }
}
```

**Comment by khyperia** [comment]
I don't think we're going to move in this direction, unfortunately :(
