### ISSUE TITLE
Make #[spirv(block)] decoration force ABI type into Struct

### ISSUE THREAD

**Issue by termhn** [EmbarkStudios/rust-gpu#391]
In a situation where one wants to use a non-struct primitive type as a push constant or uniform, you need to put it into a struct and apply the `block` decoration to it. However, if we try to just put it in a wrapper struct the ABI will not actually change. For example this

```rust
#[spirv(block)]
#[derive(Clone, Copy)]
#[allow(unused_attributes)]
pub struct Constants {
    direction: Vec2,
    _make_struct: f32,
}
```

without the `_make_struct` field, this will still be an AbiVector and so it's illegal to apply the `block` decoration to it. This also occurs for two f32s in which case it will be a ScalarPair, like here:

```rust
#[spirv(block)]
#[derive(Copy, Clone)]
#[allow(unused_attributes)]
pub struct TonemapConstants {
    pub exposure: f32,
    pub aspect: f32,
    _make_struct: f32,
}
```

It would be nice to not have to add this extra member to the struct.

**Comment by khyperia** [comment]
Just checking, does adding [`#[repr(C)]`](https://embarkstudios.github.io/rust-gpu/book/attributes.html#block) fix the issue?

**Comment by termhn** [comment]
Evidently not, doesn't compile 
![image](https://user-images.githubusercontent.com/887711/105485770-9f125680-5c6a-11eb-9372-a3ac74e7175b.png)

**Comment by termhn** [comment]
The other case also doesn't work
![image](https://user-images.githubusercontent.com/887711/105486176-5018f100-5c6b-11eb-83b6-4f8e748c84e0.png)

**Comment by khyperia** [comment]
Right, the first issue is https://github.com/EmbarkStudios/rust-gpu/issues/373, but I'm really confused by the second issue, that's really bizarre and like `#[repr(C)]` didn't actually apply (or I don't understand `#[repr(C)]`)

**Comment by eddyb** [comment]
We can fix this with a query override, and I've been meaning to try it, but would it be better to just not need `#[spirv(block)]`, and wrap every uniform automatically in an `OpTypeStruct` with a `Block` decoration?

I can't find anywhere in SPIR-V or Vulkan specs why extra layers of single-field structs would change anything - there's some stuff about `Block`-decorated `OpTypeStruct` having `Offset` decorations on their members, but I don't really see that resulting in different values than a single struct-typed field with an `Offset` of `0`.

**Comment by hrydgard** [comment]
I think auto-wrapping any structs used as various kinds of buffers would be great. 

Yeah, Vulkan shouldn't treat a 4 byte struct any different from a 128 byte one or whatever.
