### ISSUE TITLE
Convert a few GLSL shaders to Rust

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-gpu#4]
We talked about today that we should convert a few of our existing rendering shaders to Rust to see how well we could express it, even if we can't compile it to SPIRV or run them yet. Having a few GLSL or HLSL shaders here in the repo that we also have a manually converted Rust versions of, initially maybe just rough Rust psuedo code but can also try and build them in a Rust CPU crate project to actually compile it.

Can take for example the Ark mesh and sky shaders, they are quite basic and fine to duplicate to this repo for testing.

This would be a helpful guide to see what functions we would want in a shader core crate, that doesn't exist in Rust std, also for easy porting of existing shaders. And will be a guide to see what areas of Rust are the least ergonomic for shaders where we may want to have Rust language shaders to simplify it.

**Comment by XAMPPRocky** [comment]
I think this can be closed now on the rust-gpu side? We have converted quite a few shaders to Rust.
