### ISSUE TITLE
Load/Store for image texels

### ISSUE THREAD

**Issue by hrydgard** [EmbarkStudios/rust-gpu#427]
Basically, https://www.khronos.org/opengl/wiki/Image_Load_Store .

Just an issue to close when these operations are supported, couldn't find one at this time.

If there indeed is one already, please just close this as a duplicate.

**Comment by khyperia** [comment]
The basic load/store operations are implemented by https://github.com/EmbarkStudios/rust-gpu/pull/434, and further things (sampled type != float, readonly/writeonly, etc.) can have their own specific issue.
