### ISSUE TITLE
OpStore Pointer <id>'s type does not match Object <id>'s type.

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#444]
I'm sure this is a failing on my part, but I can't seem to figure out how to `OpStore` to a vector and have it work, currently I get an error.

```rust
use spirv_std::*;

trait Number {
    const WIDTH: usize;
    const SIGNED: bool;
}

impl Number for i32 {
    const WIDTH: usize = 32;
    const SIGNED: bool = true;
}

trait Vector<T, const N: usize>: Default {}

impl Vector<i32, 2> for glam::IVec2 {}

/// Signed-integer subtract of `operand` from zero. Results are computed
/// per component.
#[spirv_std_macros::gpu_only]
#[doc(alias = "OpIAdd")]
#[inline]
pub fn i_add_vector<N, V, const LEN: usize>(x: V, y: V) -> V
    where
        N: Number,
        V: Vector<N, LEN>,
{
    let mut result = V::default();

    unsafe {
        asm! {
            "%int_type = OpTypeInt {width} {sign}",
            "%vec_type = OpTypeVector %int_type {length}",
            "%x = OpLoad %vec_type {x}",
            "%y = OpLoad %vec_type {y}",
            "%result = OpIAdd %vec_type %x %y",
            "OpStore {result} %result",
            x = in(reg) &x,
            y = in(reg) &y,
            sign = const N::SIGNED as u8,
            width = const N::WIDTH,
            length = const LEN,
            result = in(reg) &mut result,
        }
    }

    result
}

#[allow(unused_attributes)]
#[spirv(fragment)]
pub fn main() {
    let vx = glam::IVec2::new(2, 5);
    let vy = glam::IVec2::new(5, 7);
    assert!(arch::i_add_vector(vx, vy) == glam::IVec2::new(7, 7));
}
```

### Error

```rust
error: invalid id:0:0 - OpStore Pointer <id> '46[%46]'s type does not match Object <id> '54[%54]'s type.
  OpStore %46 %54

  |
  = note: spirv-val failed
```

### Assembly

<details>
  <summary>Assembly</summary>
  <pre><code>
; SPIR-V
; Version: 1.3
; Generator: Google rspirv; 0
; Bound: 112
; Schema: 0
               OpCapability Shader
               OpCapability VulkanMemoryModel
               OpCapability VariablePointers
               OpCapability Int8
               OpExtension "SPV_KHR_vulkan_memory_model"
               OpMemoryModel Logical Vulkan
               OpEntryPoint Fragment %1 "main"
               OpExecutionMode %1 OriginUpperLeft
               OpName %test_project__main "test_project::main"
       %bool = OpTypeBool
      %uchar = OpTypeInt 8 0
    %v2uchar = OpTypeVector %uchar 2
%_ptr_Function_v2uchar = OpTypePointer Function %v2uchar
%_ptr_Function_uchar = OpTypePointer Function %uchar
       %uint = OpTypeInt 32 0
     %uint_0 = OpConstant %uint 0
    %uchar_0 = OpConstant %uchar 0
     %uint_1 = OpConstant %uint 1
       %true = OpConstantTrue %bool
    %uchar_1 = OpConstant %uchar 1
      %false = OpConstantFalse %bool
        %int = OpTypeInt 32 1
      %v2int = OpTypeVector %int 2
%_ptr_Function_v2int = OpTypePointer Function %v2int
       %void = OpTypeVoid
         %19 = OpTypeFunction %void
%_ptr_Function_int = OpTypePointer Function %int
%_ptr_Function__ptr_Function_v2int = OpTypePointer Function %_ptr_Function_v2int
      %int_2 = OpConstant %int 2
      %int_5 = OpConstant %int 5
      %int_7 = OpConstant %int 7
%_ptr_Function__ptr_Function_int = OpTypePointer Function %_ptr_Function_int
     %v2uint = OpTypeVector %uint 2
      %int_0 = OpConstant %int 0
         %28 = OpConstantComposite %v2int %int_0 %int_0
%_ptr_Function_bool = OpTypePointer Function %bool
    %false_0 = OpConstantFalse %bool
     %true_0 = OpConstantTrue %bool
    %false_1 = OpConstantFalse %bool
     %true_1 = OpConstantTrue %bool
    %false_2 = OpConstantFalse %bool
     %true_2 = OpConstantTrue %bool
    %false_3 = OpConstantFalse %bool
     %true_3 = OpConstantTrue %bool
    %false_4 = OpConstantFalse %bool
     %true_4 = OpConstantTrue %bool
    %false_5 = OpConstantFalse %bool
     %true_5 = OpConstantTrue %bool
         %42 = OpUndef %v2int
         %43 = OpUndef %v2uchar
         %44 = OpUndef %uchar
%test_project__main = OpFunction %void None %19
         %45 = OpLabel
         %46 = OpVariable %_ptr_Function_v2int Function
         %47 = OpVariable %_ptr_Function_v2int Function
         %48 = OpVariable %_ptr_Function_v2int Function
         %49 = OpVariable %_ptr_Function_v2int Function
         %50 = OpCompositeInsert %v2int %int_2 %42 0
         %51 = OpCompositeInsert %v2int %int_5 %50 1
         %52 = OpCompositeInsert %v2int %int_5 %42 0
         %53 = OpCompositeInsert %v2int %int_7 %52 1
         %54 = OpIAdd %v2uint %51 %53
               OpStore %46 %54
         %55 = OpCompositeInsert %v2int %int_7 %42 0
         %56 = OpCompositeInsert %v2int %int_7 %55 1
               OpStore %47 %56
         %57 = OpLoad %v2int %46
         %58 = OpLoad %v2int %47
               OpStore %48 %57
               OpStore %49 %58
         %59 = OpAccessChain %_ptr_Function_int %48 %uint_0
         %60 = OpAccessChain %_ptr_Function_int %49 %uint_0
         %61 = OpLoad %int %59
         %62 = OpLoad %int %60
         %63 = OpIEqual %bool %61 %62
         %64 = OpAccessChain %_ptr_Function_int %48 %uint_1
         %65 = OpAccessChain %_ptr_Function_int %49 %uint_1
         %66 = OpLoad %int %64
         %67 = OpLoad %int %65
         %68 = OpIEqual %bool %66 %67
         %69 = OpSelect %uchar %63 %uchar_1 %uchar_0
         %70 = OpCompositeInsert %v2uchar %69 %43 0
         %71 = OpSelect %uchar %68 %uchar_1 %uchar_0
         %72 = OpCompositeInsert %v2uchar %71 %70 1
         %73 = OpCompositeExtract %uchar %72 0
         %74 = OpINotEqual %bool %73 %uchar_0
               OpSelectionMerge %75 None
               OpBranchConditional %74 %76 %77
         %76 = OpLabel
         %78 = OpCompositeExtract %uchar %72 1
         %79 = OpINotEqual %bool %78 %uchar_0
               OpSelectionMerge %80 None
               OpBranchConditional %79 %81 %82
         %81 = OpLabel
         %83 = OpSelect %uchar %true %uchar_1 %uchar_0
               OpBranch %80
         %82 = OpLabel
               OpBranch %80
         %80 = OpLabel
         %84 = OpPhi %uchar %83 %81 %44 %82
         %85 = OpPhi %bool %true_2 %81 %false_2 %82
         %86 = OpPhi %bool %false_2 %81 %true_2 %82
               OpBranch %75
         %77 = OpLabel
               OpBranch %75
         %75 = OpLabel
         %87 = OpPhi %uchar %84 %80 %44 %77
         %88 = OpPhi %bool %85 %80 %false_3 %77
         %89 = OpPhi %bool %86 %80 %true_3 %77
               OpSelectionMerge %90 None
               OpBranchConditional %89 %91 %92
         %91 = OpLabel
         %93 = OpSelect %uchar %false %uchar_1 %uchar_0
               OpBranch %90
         %92 = OpLabel
               OpBranch %90
         %90 = OpLabel
         %94 = OpPhi %uchar %93 %91 %87 %92
         %95 = OpPhi %bool %true_4 %91 %88 %92
               OpSelectionMerge %96 None
               OpBranchConditional %95 %97 %98
         %97 = OpLabel
         %99 = OpINotEqual %bool %94 %uchar_0
        %100 = OpLogicalNotEqual %bool %99 %true
               OpSelectionMerge %101 None
               OpBranchConditional %100 %102 %103
        %102 = OpLabel
               OpBranch %104
        %104 = OpLabel
               OpBranch %105
        %105 = OpLabel
        %106 = OpPhi %bool %true_0 %104 %true_0 %107
               OpLoopMerge %108 %107 None
               OpBranchConditional %106 %109 %108
        %109 = OpLabel
               OpBranch %107
        %107 = OpLabel
               OpBranch %105
        %108 = OpLabel
               OpUnreachable
        %103 = OpLabel
               OpReturn
        %101 = OpLabel
               OpUnreachable
         %98 = OpLabel
               OpUnreachable
         %96 = OpLabel
               OpUnreachable
               OpFunctionEnd
          %1 = OpFunction %void None %19
        %110 = OpLabel
        %111 = OpFunctionCall %void %test_project__main
               OpReturn
               OpFunctionEnd

</code></pre>
</details>

**Comment by khyperia** [comment]
It looks like `%int_type` is unsigned, but the parameter vector is signed. Note the type of the `OpIAdd` is `%v2uint`, but the pointer it's storing to is `%_ptr_Function_v2int`. I'm guessing there's something up with the `SIGNED` constant (not sure what's up with your example code, as `impl Number for i32` defines `WIDTH` twice and `SIGNED` no times, so I'm not sure what the actual code looks like)

**Comment by XAMPPRocky** [comment]
> (not sure what's up with your example code, as impl Number for i32 defines WIDTH twice and SIGNED no times, so I'm not sure what the actual code looks like)

That was just a typo in the example, but you're right it was something up with the signed constant. Thank you 🙏
