### ISSUE TITLE
Vector constructor functions should ideally output a single OpCompositeConstruct instruction

### ISSUE THREAD

**Issue by expenses** [EmbarkStudios/rust-gpu#466]
This is a pretty low-priority issue, but it's something that irritates me. On [this shader playground](http://shader-playground.timjones.io/7f5f8e161ac760108cdb79f44b294c6d), the following code:

```rust
vec4(1.0, 0.0, 0.0, 1.0)
```
becomes:
```rust
%25 = OpUndef %v4float
%27 = OpCompositeInsert %v4float %float_1 %25 0
%28 = OpCompositeInsert %v4float %float_0 %27 1
%29 = OpCompositeInsert %v4float %float_0 %28 2
%30 = OpCompositeInsert %v4float %float_1 %29 3
```

when it could instead become:

```rust
%25 = OpCompositeConstruct %v4float %float_1 %float_0 %float_0 %float_1
```

Or, ideally:

```rust
%25 = OpConstantComposite %v4float %float_1 %float_0 %float_0 %float_1
```

This probably isn't going to effect performance at all, but given that `spirv-opt -O` doesn't change this (yet), it'd be nice for this change to happen at some point during the stack.

**Comment by expenses** [comment]
The best solution I can currently think of would be for `spirv-std` to have it's own vector struct that uses inline assembly for things like `new`, `mul`, etc, that glam etc. use internally when `target_arch = "spirv"` is set.

**Comment by expenses** [comment]
> The best solution I can currently think of would be for `spirv-std` to have it's own vector struct that uses inline assembly for things like `new`, `mul`, etc, that glam etc. use internally when `target_arch = "spirv"` is set.

This would also mean that we could do a single `OpMatrixTimesVector` instruction instead of a while bunch of `OpFMul` and `OpFAdd`s.

**Comment by msiglreith** [comment]
Smaller spirv code is one of the main reasons I currently roll my own instead of glam. Also, using the intrinsics may helps with driver generation. e.g AMD drivers for example weren't able to derive operand modifiers for `f32::clamp` as it's implemented as `min().max()` :(

**Comment by lachlansneff** [comment]
Yeah, I agree as well. std-spirv should have it's own vectors and matrix types. Easier for the backend to special-case them anyhow.

**Comment by eddyb** [comment]
You'd still have the issue of things generating the element-wise insertion from various kinds of code.

AFAIK the only ways you'll get `OpConstantComposite` is generating it via inline `asm!` (of limited use), or writing a pass.

My opinion, as expressed in the meeting, is that would normally be part of a basic (constant) folding pass and I'm a bit baffled `spirv-opt` is missing it - but then again, it's missing a bunch of things *sigh*.

We could implement it on our own, or in `spirv-opt`.

Is there any particular reason to do it, other than people reading SPIR-V? Also, if you're familiar with LLVM IR, the element-wise insertion style will be natural (AFAIK there is no whole-aggregate-at-once construction at all in LLVM, outside of constants).

**Comment by expenses** [comment]
> Though, is there any particular reason to do it, other than people reading SPIR-V? 

I mostly read SPIR-V because of the optimisations that `spirv-opt` is missing :P

**Comment by khyperia** [comment]
I don't think fixing this is on our roadmap right now as it doesn't affect performance, only spir-v binary size, and TBH this transformation of "`OpCompositeInsert` on `OpUndef` -> `OpCompositeConstruct`" should probably go in spirv-opt, not here.
