### ISSUE TITLE
.abs() and .signum() cause 64-bit integer instruction generation

### ISSUE THREAD

**Issue by hrydgard** [EmbarkStudios/rust-gpu#468]
This is arguably not rust-gpu's fault, but num-traits, but it'll happen again, so we need a record of it.

Using vector abs ends up generating 64-bit ops due to https://github.com/rust-num/num-traits/blob/47d69223ce7707ebbf8a91c3e6b3997e48653feb/src/float.rs#L762 .

Also see the following image:

![image](https://user-images.githubusercontent.com/130929/109947514-aef56f80-7cd9-11eb-8def-fd142aaf9c9a.png)

Ideally of course, abs should just generate a SPIR-V abs instruction instead of doing bithacks.

**Comment by khyperia** [comment]
Just adding here that the error reporting system for this is absolutely horrible right now, and should be improved (the way I got that screenshot was hacking in random stuff to the compiler to add error points to get a backtrace to figure out what was wrong, see the `nyaah` error message in the screenshot, haha).

The way that would be done is implementing the capability computation system @XAMPPRocky came up with, tracked in https://github.com/EmbarkStudios/rust-gpu/issues/42 (I'll add the system to a comment there)

**Comment by hrydgard** [comment]
Another affected function is `signum`.

**Comment by khyperia** [comment]
Ah, never actually wrote this down, `.abs()` is fixed by https://github.com/rust-num/num-traits/pull/196, and I don't believe `copysign` exists in num-traits for some reason. `signum` is still broken, though, going to see if I can PR a fix now. However, https://github.com/rust-num/num-traits/pull/196 isn't in any num-traits release yet, so it's still broken for us.

**Comment by XAMPPRocky** [comment]
@khyperia I opened a PR for it awhile ago https://github.com/rust-num/num-traits/pull/207. I've sent them a friendly ping to look at it again.

**Comment by oisyn** [comment]
num-traits issue was merged into main on May 3. Everything seems to work as expected now.
