### ISSUE TITLE
Ash example runner segfaults on Intel HD620

### ISSUE THREAD

**Issue by yozhijk** [EmbarkStudios/rust-gpu#474]
example-runner-ash immediately segfaults on Intel HD 620 in Ubuntu 20.10, while example-runner-wgpu runs fine.

### Expected Behaviour
example-runner-ash is expected to run without any issues. 

### Example & Steps To Reproduce
1. Clone the repo
2. cargo run --bin example-runner-ash

Output:
```
Finished dev [unoptimized + debuginfo] target(s) in 0.10s
Running `target/debug/example-runner-ash
Finished release [optimized] target(s) in 0.07s
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

Segmentation fault (core dumped)
```

## System Info

 - Rust: rustc 1.52.0-nightly (476acbf1e 2021-03-03)
 - OS: Kubuntu 20.10 *
 - GPU: Intel UHD Graphics 620 
 - SPIR-V: v2020.3 unknown hash, 2020-06-17T19:41:32

### Backtrace
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
thread 'main' panicked at 'Could not find librustc_codegen_spirv.so in library path', crates/spirv-builder/src/lib.rs:120:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/476acbf1e9965b5e95c90f0d7d658709812b7003/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/476acbf1e9965b5e95c90f0d7d658709812b7003/library/std/src/panicking.rs:435:5
   2: spirv_builder::find_rustc_codegen_spirv
             at ./crates/spirv-builder/src/lib.rs:120:5
   3: spirv_builder::invoke_rustc
             at ./crates/spirv-builder/src/lib.rs:132:31
   4: spirv_builder::SpirvBuilder::build
             at ./crates/spirv-builder/src/lib.rs:82:28
   5: example_runner_ash::compile_shaders
             at ./examples/runners/ash/src/main.rs:130:40
   6: example_runner_ash::main
             at ./examples/runners/ash/src/main.rs:41:19
   7: core::ops::function::FnOnce::call_once
             at /home/yozhijk/.rustup/toolchains/nightly-2021-03-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
```

**Comment by khyperia** [comment]
This seems weird. On your first log, it appears to be a segfault. On the second log, it appears to be a panic, not a segfault. How did you obtain the second backtrace?

Anyway, as to the actual problem, it looks like you're not running the executable under `cargo run` - "Could not find librustc_codegen_spirv.so in library path" is an error that happens when executing `./target/debug/example-runner-ash` directly, instead of via `cargo run -p example-runner-ash`.

**Comment by yozhijk** [comment]
Yes, I think you can disregard this backtrace. I have obtained it trying to debug an executable using gdb, so that was definitely caused by not running under cargo. How do I get a proper backtrace?

**Comment by khyperia** [comment]
Your best bet is probably to open up the core dump with gdb or lldb - `Segmentation fault (core dumped)` means the core dump went _somewhere_. I don't know where core dumps go on Kubuntu, you might need to do some googling and twiddle some settings, it looks like Ubuntu at least (idk about Kubuntu) doesn't save core dumps by default?

Alternatively, you could do some debugging and figure out the path `LD_LIBRARY_PATH` is being set to, and then set that env var before running the executable.

**Comment by XAMPPRocky** [comment]
The Ash runner has just gone through modifications, can you verify you're still getting this on the latest code?

**Comment by yozhijk** [comment]
Yes, that fixed it, thanks!
