### ISSUE TITLE
Malformed `asm!` causes opaque storage class inference conflict errors and/or ICEs

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#477]
I was trying to get the type of a pointer in a generic fashion, however I've been running into some errors in using inference that are preventing me from doing so. Version 1 of the ASM code causes an `inference conflict` error, and the second version causes an ICE.

cc @eddyb 

### Code

```rust
#![no_std]
#![feature(register_attr, asm)]
#![register_attr(spirv)]

use spirv_std::{scalar::Scalar, storage_class::Input};

pub fn ptr_inference(input: &Input<f32>) {
    let mut result = 0.0;

    // Version 1
    unsafe {
        asm! {
            "%result = OpLoad _ {ptr}",
            "OpStore {result} %result",
            ptr = in(reg) input,
            result = in(reg) &mut result
        }
    }

    // Version 2
    unsafe {
        asm! {
            "%ptr_type = OpTypePointer Generic _",
            "%result = OpLoad %ptr_type {ptr}",
            "OpStore {result} %result",
            ptr = in(reg) input,
            result = in(reg) &mut result
        }
    }
}

#[spirv(fragment)]
pub fn main(x: Input<f32>) {
    ptr_inference(&x);
}
```

### Inference Conflict Error
```
inference conflict: Concrete(IdRef(21)) vs Instance(Instance { generic_id: 3, generic_args: InferVar(7)..InferVar(8) })
    in OpStore 23 27
```

### ICE Error
```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', crates/rustc_codegen_spirv/src/builder/spirv_asm.rs:296:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/EmbarkStudios/rust-gpu/issues/new

note: rustc 1.52.0-nightly (476acbf1e 2021-03-03) running on x86_64-apple-darwin

note: compiler flags: -Z unstable-options -Z codegen-backend=/Users/erin.power/src/scratchpad/rustgpu.dylib -Z symbol-mangling-version=v0 -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type dylib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
note: `rust-gpu` version 0.3.0
```

**Comment by eddyb** [comment]
```
    in OpStore 23 27
```
Wait, how are you getting that? Should be impossible now that we've updated `rspirv` to include @khyperia's https://github.com/gfx-rs/rspirv/pull/184.

<hr/>

I'm not sure why you get an ICE for `%ptr_type = OpTypePointer Generic _`, but that's not supported - we can only "infer" types (it's really more "deduce") in *Result Type* position.

Just tried it and before the ICE you get an "error: expected ID" - sadly it doesn't point to the line, but it does point to the right `asm!`.

<hr/>

Anyway, it turns out that this is just a malformed `asm!` that we can't validate ourselves, your `input` is `&Input<T>` which is a pointer to a struct that contains a pointer - this, for example, works just fine:
```rust
    unsafe {
        asm! {
            "%result = OpLoad _ {ptr}",
            "OpStore {result} %result",
            ptr = in(reg) &**input,
            result = in(reg) &mut result
        }
    }
```

**Comment by eddyb** [comment]
Even if this is mostly just a "broken `asm!` results in strange errors", I think we should track making all the errors here better.

**Comment by XAMPPRocky** [comment]
@eddyb Just to be clear, what's malformed about this asm?

```rust
        asm! {
            "%u32 = OpTypeInt 32 0",
            "%scope = OpConstant %u32 0",
            "%semantics = OpConstant %u32 0",
            "%result = OpAtomicLoad _ {ptr} %scope %semantics",
            "OpAtomicStore {result} %scope %semantics %result",
        }
```

**Comment by eddyb** [comment]
That `asm!` takes in two values (`{ptr}` and `{result}`), and its validity depends on their types, can't really be malformed on its own as-is, it's just incomplete, really.
My guess is that `typeof(*ptr) != typeof(*result)`, but if it's not that, it could be a bug elsewhere.

**Comment by XAMPPRocky** [comment]
I also get the inference bug on the following code.

```rust
pub unsafe fn atomic_store<S: spirv_std::scalar::Scalar>(ptr: &mut S, value: S) {
    asm! {
        "%u32 = OpTypeInt 32 0",
        "%scope = OpConstant %u32 0",
        "%semantics = OpConstant %u32 0",
        "%value = OpLoad _ {value}",
        "OpAtomicStore {ptr} %scope %semantics {value}",
        ptr = in(reg) ptr,
        value = in(reg) &value,
    }
}


#[spirv(fragment)]
pub fn main(mut output: Image<f32>) {
    unsafe {
        spirv_std::arch::atomic_store(&mut *output, 5.0);
    }
}
```

**Comment by eddyb** [comment]
@XAMPPRocky That's also malformed `asm!`, I assume you meant to write `%value` instead of `{value}` - should probably avoid reusing names between the two, and call the input e.g. `{value_ref}` instead.

**Comment by XAMPPRocky** [comment]
@eddyb Yep, only caught that after I posted it. 😅 It works when fixed.

**Comment by khyperia** [comment]
I don't think improving the error messages of `asm!` is important to us right now, and ICE'ing is probably fine (it ICEs in a whole bunch of other places, in a way that I think we would need to do validation on the instructions ourselves, and that's just too much)

**Comment by eddyb** [comment]
> Wait, how are you getting that? Should be impossible now that we've updated `rspirv` to include @khyperia's gfx-rs/rspirv#184.

Well I just figured that one out: we never did bump our dependency to include gfx-rs/rspirv#184.

I'm not sure what happened, because I clearly recall getting its effect locally.
I either forgot to commit, or it was in a commit that got lost in a rebase.
