### ISSUE TITLE
Document numthreads(x, y, z) attribute

### ISSUE THREAD

**Issue by Jasper-Bekkers** [EmbarkStudios/rust-gpu#478]
Compute shaders need to be able to specify how many threads they use as an entry point attribute. Right now compute shaders are 1x1x1 which wastes a significant part of the machine's performance.

**Comment by Hentropy** [comment]
I was looking at implementing #478 but it seems it's already implemented.  LocalSize can be specified like other execution modes/entry point decorations: #[spirv(gl_compute(local_size_x = 23) or #[spirv(gl_compute(local_size_x = 3, local_size_y = 6, local_size_z = 5).

**Comment by XAMPPRocky** [comment]
@Hentropy Thank you for investigating! I've updated the issue title to be about documenting the attribute. It should probably have a section in the "Attributes" chapter. https://embarkstudios.github.io/rust-gpu/book/attributes.html

**Comment by XAMPPRocky** [comment]
@Hentropy Do you want to add a section in the book about the new syntax for `numthreads`? 🙂

**Comment by Hentropy** [comment]
Done in PR #499
