### ISSUE TITLE
Scalarizer-checker

### ISSUE THREAD

**Issue by Jasper-Bekkers** [EmbarkStudios/rust-gpu#49]
Much like the borrow checker checks lifetimes, I think it might be important for a modern, safe GPU language to be able to check and verify access to scalar registers and to validate scalar control flow.

Right now the concept of scalars isn't exposed in SPIR-V as a first class citizen (and it might never be), however experiments in ISPC and discussions with IHVs have show that this is indeed an issue. Doing this properly can mean both a performance win (more scalarized code is typically better) and a safety win (e.g. preventing writing to vector registers from scalar branches would be a simple example).

https://ispc.github.io/ispc.html#uniform-and-varying-qualifiers
https://ispc.github.io/ispc.html#uniform-control-flow

To be clear, this isn't about the distinction from float and Vec4, this is about sgpr vs vgrp.

Examples include GCN/RDNA's `s_` namespaced registers and instructions (as opposed to the `v` ones https://developer.amd.com/wp-content/resources/RDNA_Shader_ISA.pdf). And NVIDIA's URX vs RX registers in Turing: https://docs.nvidia.com/cuda/cuda-binary-utilities/index.html

**Comment by Tobski** [comment]
As a bit of additional input here, since I forgot to put it on before, there are optimisations which some vendors can take advantage of when knowing values are uniform at other scopes too - e.g. uniform across the device, across a workgroup, across a triangle...

SGPR/VGPR distinctions as on AMD hardware are but the tip of the iceberg. Being able to know/validate the uniformity at compile time (and validate at runtime when necessary) would be incredibly useful. The analogy to the rust borrow checker is quite apt I think.

I suspect this falls into a similar design space as say value range checking, so might run into some of the same design issues discussed on this long running issue: https://github.com/rust-lang/rfcs/issues/671 - albeit applied differently.

**Comment by Tobski** [comment]
Ok so turning this into something a _bit_ more concrete, I think I'd propose three new attributes that affect struct definitions for shader inputs:

```rust
#[SubgroupVisible]
#[WorkgroupVisible]
#[DeviceVisible]
```

Each of these attributes modifies what happens during borrow and drop, and memory semantics used for OpLoad/OpStore when accessing references to these structs.

Note: **If none of these attributes are present it should be a compiler error to borrow a mutable reference from the struct**, (unless the code is declared unsafe?).

## Scope

The word before "Visible" in the attribute determines the scope at which writes to the structure are made visible to other shader invocations.
So "SubgroupVisible" indicates that other invocations in the same subgroup can see values written by other invocations, assuming correct synchronization.
This scope is used as the `%scope` operand for the instructions detailed below.

## Acquire on Borrow

When a reference is borrowed from the structure, an [OpMemoryBarrier](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpMemoryBarrier) should be performed as follows:

```spir-v
OpMemoryBarrier %scope Acquire
```

## Release on Drop

When a reference to the structure is dropped, an [OpMemoryBarrier](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpMemoryBarrier) should be performed as follows:

```spir-v
OpMemoryBarrier %scope Release
```

## Loads

When a reference to the structure is read from, an [OpLoad](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpLoad) should be generated with the following [Memory Operands](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpStore): 

```spir-v
%value = OpLoad %pointer MakePointerVisible|NonPrivatePointer %scope
```

## Stores

When a reference to the structure is written to, an [OpStore](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpStore) should be generated with the following [Memory Operands](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#Memory_Operands):

```spir-v
OpStore %pointer %value MakePointerAvailable|NonPrivatePointer %scope
```

**Comment by khyperia** [comment]
This sort of compiler tech is way too far in the future (at least a year, probably two, *if* we're actively working on chugging through compiler issues) and not on our roadmap of use cases, so I don't think it's useful to track this work right now.
