### ISSUE TITLE
Unable to Implement Grad Operand for OpImageSampleExplicitLod in spirv-std

### ISSUE THREAD

**Issue by DeanBDean** [EmbarkStudios/rust-gpu#500]
### Expected Behaviour
The test `cargo test image_sample_gradient` on [this branch](https://github.com/DeanBDean/rust-gpu/tree/add-image-sample-explicit-lod) should not fail in the `asm` macro with the message `expected operand after instruction: ImageSampleExplicitLod`

### Example & Steps To Reproduce

1. Pull this branch, https://github.com/DeanBDean/rust-gpu/tree/add-image-sample-explicit-lod
2. run `cargo test image_sample_gradient`

## System Info

 - Rust: [rustc 1.52.0-nightly (f5d8117c3 2021-03-16)]
 - OS: [macOS 10.15.7]
 - GPU: [Intel(R) UHD Graphics 630]
 - SPIR-V: [SPIRV-Tools v2020.7 unknown hash, 2021-02-18T19:18:50]

## Backtrace

<details><summary>Backtrace</summary>
<p>

```
error: expected operand after instruction: ImageSampleExplicitLod
   --> /Users/10529/repos/rust-gpu/crates/spirv-std/src/textures.rs:202:13
    |
202 | /             asm!(
203 | |                 "%image = OpLoad _ {this}",
204 | |                 "%sampler = OpLoad _ {sampler}",
205 | |                 "%coordinate = OpLoad _ {coordinate}",
...   |
214 | |                 gradient = in(reg) &gradient,
215 | |             );
    | |______________^

error: aborting due to previous error

error: could not compile `test-project`
```

</p>
</details>

**Comment by msiglreith** [comment]
`Grad` uses two operands dx and dy. In your PR you passed them as one vec2 if I see it correctly

**Comment by DeanBDean** [comment]
Ah thank you, I was confused by the spec, I thought you were passing in dx/dy

**Comment by XAMPPRocky** [comment]
Closing as resolved. 🙂
