### ISSUE TITLE
Capability StorageImageWriteWithoutFormat is required to write to storage image

### ISSUE THREAD

**Issue by FVershinin** [EmbarkStudios/rust-gpu#527]
I have got an error when try to write to storage image:
```
I/VALIDATION: UNASSIGNED-CoreValidation-Shader-InconsistentSpirv(ERROR / SPEC): msgNum: 0 - SPIR-V module not valid: Capability StorageImageWriteWithoutFormat is required to write to storage image
      OpImageWrite %263 %93 %220
    
        Objects: 1
            [0] 0, type: 0, name: NULL
```
```rust

#[spirv(block)]
pub struct PointsBuffer {
    points: [UVec2; 100],
}

#[spirv(compute(threads(1)))]
pub fn main_cs(
    #[spirv(global_invocation_id)]
    id: Input<UVec3>,
    #[spirv(descriptor_set = 0, binding = 0)]
    points_buffer: StorageBuffer<PointsBuffer>,
    #[spirv(descriptor_set = 0, binding = 1)]
    image: UniformConstant<StorageImage2d>,
) {
    let position = id.xy();
    for i in 0..100usize {
        let p0 = &points_buffer.points[i];
        let p1 = &points_buffer.points[i + 1];
        if p0.x == position.x && p1.y == position.y {
            unsafe {
                image.write(position, vec2(1.0,  0.0));
            };
        }
    }
}
```

## System Info
 - Rust: 1.52.0-nightly
 - OS: Android
 - Spirv: 1.0
 - Vulkan: 1.0,

**Comment by XAMPPRocky** [comment]
Thank you for your issue! The minimum [version SPIR-V and Vulkan that we currently support](https://embarkstudios.github.io/rust-gpu/book/platform-support.html) is 1.3+ and 1.1+ respectively. You could try adding `unsafe { asm!("OpCapability StorageImageWriteWithoutFormat"); }` to the top of your function body and see if that works.

**Comment by khyperia** [comment]
Question for us: We have a [test for this](https://github.com/EmbarkStudios/rust-gpu/blob/7c0c467e96579cb82a81875d139047351bc4a622/tests/ui/image/write.rs) that doesn't include `StorageImageWriteWithoutFormat`. However, the latest spec clearly states

> The Image Format must not be Unknown, unless the StorageImageWriteWithoutFormat Capability was declared.

Why does that test pass? It shouldn't.

**Comment by FVershinin** [comment]
> Thank you for your issue! The minimum [version of SPIR-V and Vulkan that we currently support](https://embarkstudios.github.io/rust-gpu/book/platform-support.html) is 1.3+ and 1.1+ respectively. You could try adding `unsafe { asm!("OpCapability StorageImageWriteWithoutFormat"); }` to the top of your function body and see if that works.

It works, Thanks.

**Comment by XAMPPRocky** [comment]
I can reproduce this locally. Validation fails for Vulkan environments not SPIR-V environments. I'll get to adding environments since that will let add a test to make sure this behaves correctly.

**Comment by khyperia** [comment]
I believe this test has been implemented, and so this has been fixed.
