### ISSUE TITLE
Types mismatch when compiling for kernel

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#550]
After the discussion on discord about kernel mode, I tried to compile our only compute test for kernel mode to see if it would work. First error I ran into was that it had a runtime array which was a hard error for kernel mode. However after removing that part, I ran into this weird types mismatch error, but following code compiles when kernel mode is not enabled.

### Source

```rust
// compile-flags: -Ctarget-feature=+kernel
use glam::*;

#[spirv(compute(threads(1)))]
pub fn main_cs(
    #[spirv(global_invocation_id)]
    id: UVec3,
    #[spirv(uniform_constant, descriptor_set = 1, binding = 1)]
    image: &spirv_std::StorageImage2d,
) {
    unsafe { asm!("OpCapability StorageImageWriteWithoutFormat") };
    let position = id.xy();
    for i in 0..100usize {
        let p0 = uvec2(0, 1);
        let p1 = uvec2(1, 2);
        if p0.x == position.x && p1.y == position.y {
            unsafe {
                image.write(position, vec2(1.0,  0.0));
            };
        }
    }
}
```

### Error
```
error: Types mismatch for "_ZN63_$LT$I$u20$as$u20$core..iter..traits..collect..IntoIterator$GT$9into_iter17h049b3904b00a9fcdE"
```

**Comment by khyperia** [comment]
Also, just for context and clarity of priority, this is extremely low priority and probably won't/shouldn't get looked at by the team for... probably at least another 6 months, tbh
