### ISSUE TITLE
Texel Buffers (Uniform + Storage)

### ISSUE THREAD

**Issue by hrydgard** [EmbarkStudios/rust-gpu#569]
Vulkan Texel buffers are (potentially) large 1-D images that are not backed by image objects, instead they're backed by a [VkBufferView](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkBufferViewCreateInfo.html) specifying a range (and format, for free conversion) of a VkBuffer.

These can be either read-only (Uniform Texel Buffers) or read/write (Storage Texel Buffers).

The corresponding SPIR-V can be found at https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_vulkan_glsl.txt#L370 .

Essentially, it's just texelFetch on an image with Dim = Buffer.

Historically, they are yet another historical artifact that predate storage buffers, they existed as a special kind of 1D textures in OpenGL to access large arbitrary data. Effectively it's using a texture unit on a linear buffer, so they still have advantages such as free format conversion from packed integer formats to float, and accessing unaligned formats like R32G32B32_FLOAT , which is good in raytracing shaders for grabbing vertex data through bindless arrays of these for doing stuff like normal or UV coordinate interpolation after a hit

https://github.com/EmbarkStudios/rust-gpu/issues/450 is related.

**Comment by XAMPPRocky** [comment]
> so they still have advantages such as free format conversion from packed integer formats to float, and accessing unaligned formats like R32G32B32_FLOAT

Are formats like `R32G32B32_FLOAT` required? AFAICT SPIR-V doesn't have those in the spec, and doesn't have an extension that adds them.

**Comment by XAMPPRocky** [comment]
Both Uniform and Storage Texel Buffers are implemented in #359. With that PR you'd write the types from your example as follows:

```rust
use spirv_std::Image;

type UniformBuffer = Image!(buffer, type=f32, sampled);
type StorageBuffer = Image!(buffer, format=r32f, sampled=false);

**Comment by hrydgard** [comment]
@XAMPPRocky  SPIR-V doesn't care about the format. It's like a texture, conversion happens on load.

**Comment by XAMPPRocky** [comment]
these are now available in main.
