### ISSUE TITLE
Support #[spirv(<builtin>)] attributes on struct fields for geometry shaders

### ISSUE THREAD

**Issue by Arc-blroth** [EmbarkStudios/rust-gpu#579]
# Background

In OpenGL and Vulkan, geometry shaders are given inputs of an entire primitive rather than a single vertex. This means that each shader invocation is [passed an array for each piece of input data][1].

Currently, it is impossible to port the following code to rust-gpu:
```glsl
#version 450

layout (triangles, invocations = 1) in;
layout (triangle_strip, max_vertices = 3) out;

void main() {
    for (int i = 0; i < 3; i++) {
        gl_Layer = gl_InvocationID;
        gl_Position = gl_in[i].gl_Position;
        EmitVertex();
    }
    EndPrimitive();
}
```
since `gl_in` is an array of `gl_PerVertex` structs, whose members are builtins. In SPIR-V, this is represented as
```asm
OpMemberDecorate %gl_PerVertex 0 BuiltIn Position
OpMemberDecorate %gl_PerVertex 1 BuiltIn PointSize
OpMemberDecorate %gl_PerVertex 2 BuiltIn ClipDistance
OpMemberDecorate %gl_PerVertex 3 BuiltIn CullDistance
OpDecorate %gl_PerVertex Block
; ...
%gl_PerVertex = OpTypeStruct %v4float %float %_arr_float_uint_1 %_arr_float_uint_1
%gl_in = OpVariable %_ptr_Input__arr_gl_PerVertex_0_uint_3 Input
```
However, rust-gpu currently doesn't allow decorating struct members with `#[spirv(position)]` or other builtins, and compiling this will fail:
```rust
use glam::Vec4;
use spirv_std::arch::{end_primitive, emit_vertex};

pub struct PerVertex {
    // "attribute is only valid on a parameter of an entry-point function" error
    #[spirv(position)] pub gl_position: Vec4,
    #[spirv(point_size)] pub gl_point_size: f32,
    #[spirv(clip_distance)] pub gl_clip_distance: [f32; 1],
    #[spirv(cull_distance)] pub gl_cull_distance: [f32; 1],
}

#[spirv(geometry(triangles, invocations = 1, output_triangle_strip, output_vertices = 3))]
pub fn main(
    gl_in: [PerVertex; 3],
    #[spirv(invocation_id)] gl_invocation_id: u32,
    #[spirv(layer)] gl_layer: &mut u32,
    #[spirv(position)] gl_position: &mut Vec4,
) {
    for i in 0..3 {
        *gl_layer = gl_invocation_id;
        *gl_position = gl_in[i].gl_position;
        unsafe { emit_vertex(); }
    }

    unsafe { end_primitive(); }
}
```

# Proposal

Allow `#[spirv(position)]` and other builtin attributes to be applied to struct members _if and only if_ the containing struct appears in the interface of an entrypoint. This translates to an `OpMemberDecorate` on that struct member in SPIR-V.

Quoting from the SPIR-V [validation rules][2], the compiler will also need to validate that:
> A BuiltIn Decoration must be applied only as follows:
> - If applied to a structure-type member, all members of that structure type must also be decorated with BuiltIn. (No allowed mixing of built-in variables and non-built-in variables within a single structure.)
> - If applied to a structure-type member, that structure type must not be contained as a member of another structure type.
> - There must be no more than one object per Storage Class that contains a structure type containing members decorated with BuiltIn, consumed per entry-point.

This proposal will probably require at least some internal changes on where and when attributes are validated.

[1]: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/vkspec.html#geometry-input
[2]: https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#_a_id_validation_a_validation_rules

**Comment by termhn** [comment]
As of now, we've determined that geometry (and mesh and tesselation) shaders are out of scope for the rust-gpu project. Geometry shaders are notoriously slow on most graphics architectures aside from some Intel ones, and should generally be avoided for new code... much of their basic functionality can be recreated with standard vertex shaders indexing into external data sets, and for more complex ones, rewriting them as compute shaders is probably the better choice. That said, they can potentially be valuable for purposes of porting old code, so we're not ruling it out altogether in the long run... though it's unlikely to be a priority for a significant period of time.

In terms of your proposal, is there a use case for this change outside of the one outlined in geometry shaders? If there's a compelling one, this could still be an interesting change, though if it's just for geometry shaders we're probably going to have to close this as out of scope for now.

**Comment by Arc-blroth** [comment]
Sadly I can't really think of any usecase for this outside of geometry shaders, since builtins can be passed as seperate entrypoint arguments in all other cases. Thanks for reviewing this MCP anyways!

**Comment by termhn** [comment]
Of course :) Thanks for your interest and for writing it.

**Comment by Cazadorro** [comment]
> (and mesh and tesselation)

Wait, I knew you guys were entirely avoiding dealing with geometry shaders, but why *mesh* shaders?  Those are both new *and established* being implemented on two generations of Nvidia cards and also the latest AMD cards, and both the new consoles have mesh shader support.  In fact we could conceivably see mesh shaders as *the* way to go for rendering after a couple years for modern hardware, forgoing *vertex shaders*.   If anything mesh shaders should be the next target after compute shaders are stable and complete, not an afterthought like geometry shaders.

**Comment by termhn** [comment]
> > (and mesh and tesselation)
> 
> Wait, I knew you guys were entirely avoiding dealing with geometry shaders, but why _mesh_ shaders? Those are both new _and established_ being implemented on two generations of Nvidia cards and also the latest AMD cards, and both the new consoles have mesh shader support. In fact we could conceivably see mesh shaders as _the_ way to go for rendering after a couple years for modern hardware, forgoing _vertex shaders_. If anything mesh shaders should be the next target after compute shaders are stable and feature complete, not an afterthought like geometry shaders.

Mesh shaders are definitely in a different category than geometry shaders, it's just that they're also under the broad category of out of scope, for now, since we aren't using them ourselves. They're definitely much more likely to get support than geometry or tessellation shaders, though.
