### ISSUE TITLE
v0 mangling support for const generics

### ISSUE THREAD

**Issue by ElectronicRU** [EmbarkStudios/rust-gpu#642]
As we're currently using a const generic type parametrized by enums for Image types, v0 mangling cannot be fully supported because it doesn't handle non-basic-type const generic parameters and panics.

Once rust-lang/rust#61486 is implemented, we can switch back to v0 support.

**Comment by eddyb** [comment]
Self-assigned because I've been working on this (see https://github.com/rust-lang/rust/pull/87194).
