### ISSUE TITLE
Add type aliases for common `Image!` formats

### ISSUE THREAD

**Issue by khyperia** [EmbarkStudios/rust-gpu#644]
For example, `pub type Image2d = Image!(2D, type=f32, sampled);`. I'd want to add aliases for all the names we have now, probably plus a few more (`Image1d`, `Image3d`, etc.).

Advantages:

- The `Image!` macro is a little verbose and wordy for something as common as a 2d texture. Users can write their own typedefs, but that seems to be rare to actually do in practice and if the typedef were in spirv-std, the typedef would be used far more often.
- It lets people get up and running faster: instead of needing to figure out the `Image!` macro (reading docs, etc.), they can just use their previous graphics knowledge of a type called "image2d"/"texture2d" and use that off the bat.
- It's a nice learning example for people goto-def'ing: seeing practical differences between how `type Image2d` and `type StorageImage` differ in their `Image!` arguments is a nice teaching example.

Disadvantages:
- It doesn't force people to learn the `Image!` macro, and some people might miss how flexible `Image!` actually is.
- I wouldn't have to write `Image!` with an exclamation point as much, which, [as `SHARKS!` has taught us](https://www.youtube.com/watch?v=_8xhdL8BPvU), is clearly a bad thing

---

Not sure if this is actually deserving of an MCP, but I'm using the tag as basically a reminder that I want to discuss it in the weekly meeting, as I think I do want to discuss this in the weekly meeting.

**Comment by hrydgard** [comment]
to be more analogous to GLSL, might consider adding Image2dU = Image!(2D, type=u32, sampled) for unsigned integer images, and similarly Image2dI for the signed case. Although that 'I' looks a bit weird there...
