### ISSUE TITLE
Unfindable spirv-builder crate and undocumented target in latest git version

### ISSUE THREAD

**Issue by Wicpar** [EmbarkStudios/rust-gpu#649]
### Expected Behaviour
use the spirv-builder crate like in the [documentation](https://embarkstudios.github.io/rust-gpu/book/writing-shader-crates.html)

### Example & Steps To Reproduce

1. follow the steps described in the documentation
2. the `spirv-builder = "0.1.0"` crate is some kind of zombie crate that doesn't have the spirv_builder mod in it. Other versions are not found at all
3. if added through the git, it requires an undocumented target parameter, supposedly for the cargo command.

## System Info

 - Rust: rustc 1.54.0-nightly
 - OS: Windows 10 Version 10.0.19041 Build 19041
 - GPU: RTX 3090 eGPU
 - SPIR-V: SPIRV-Tools v2021.2-dev v2021.1-31-gc05f7441

## Backtrace

<details><summary>Backtrace</summary>
<p>

```
Caused by:
  process didn't exit successfully: `[redacted]\target\debug\build\rust_engine-d11c877f42ad3630\build-script-build` (exit code: 101)
  --- stderr
  error: failed to run `rustc` to learn about target-specific information
  Caused by:
    process didn't exit successfully: [redacted]\.cargo\bin\rustc.exe - --crate-name ___ --print=file-names -Z codegen-backend=[redacted]\target\debug\rustc_codegen_spirv.dll -Zsymbol-mangling-version=legacy --target "SPIR-V 1.0" --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
    --- stderr
    error: Error loading target specification: Could not find specification for target "SPIR-V 1.0". Run `rustc --print target-list` for a list of built-in targets
  thread 'main' panicked at 'Did not find output file in rustc output', [redacted]\.cargo\git\checkouts\rust-gpu-e0a37a82a46176e6\486a3ce\crates\spirv-builder\src\lib.rs:458:10
  stack backtrace:
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Process finished with exit code 101
```

</p>
</details>

**Comment by Wicpar** [comment]
For those encountering the problem, the target is: `spirv-unknown-spv1.4`, `1.4` can be changed to the appropriate version.

**Comment by khyperia** [comment]
Ah, looks like we forgot to update that bit of the documentation when we added the target parameter. The targets [are documented here in the book](https://embarkstudios.github.io/rust-gpu/book/platform-support.html), but yeah, we should update that page.

Also, you are correct in that we do not publish `spirv-builder` to crates.io because we don't feel it's ready yet - I'm kind of baffled how what we've been saying of "use the git version" hasn't gotten into that page, thanks for pointing that out.

**Comment by Wicpar** [comment]
@khyperia thank you :)
