### ISSUE TITLE
Expose floating point format conversion operations (16 <-> 32 bits)?

### ISSUE THREAD

**Issue by hrydgard** [EmbarkStudios/rust-gpu#707]
HLSL and GLSL both have operations that convert between 16 and 32-bit floating point formats.

In GLSL they look like this, packing/unpacking two 16-bit floats to/from an uint:

```
vec2 unpackHalf2x16(uint v);
uint packHalf2x16(vec2 v);
```

HLSL has scalar (non-pack/unpack) operations only:

```
uint f32tof16(in float value);
float f16tof32(in uint value);
```

I have not looked in detail yet about what actual SPIR-V the GLSL operations become. Possibly there's some capability required to get these natively?

**Comment by khyperia** [comment]
The scalar ones in HLSL compile to doing the vector op (inserting a 0.0, or extracting the x component, as needed). I figured out what the impl should be, so just writing it down here until I can get around to putting them in spirv-std (probably want helpers for the scalar versions that call through to these, too):

```rust
fn pack_half2x16(vec: Vec2) -> u32 {
    let result;
    unsafe {
        asm!(
            "%glsl = OpExtInstImport \"GLSL.std.450\"",
            "%uint = OpTypeInt 32 0",
            "%vec = OpLoad _ {vec}",
            // 58 = PackHalf2x16
            "{result} = OpExtInst %uint %glsl 58 %vec",
            vec = in(reg) &vec,
            result = out(reg) result,
        );
    }
    result
}
fn unpack_half2x16(int: u32) -> Vec2 {
    let mut result = Default::default();
    unsafe {
        asm!(
            "%glsl = OpExtInstImport \"GLSL.std.450\"",
            "%float = OpTypeFloat 32",
            "%vec2 = OpTypeVector %float 2",
            // 62 = UnpackHalf2x16
            "%result = OpExtInst %vec2 %glsl 62 {int}",
            "OpStore {result} %result",
            int = in(reg) int,
            result = in(reg) &mut result,
        );
    }
    result
}
```

**Comment by hrydgard** [comment]
I don't think scalar versions are that important since they are trivially implementable in terms of these two. But sure, could be added just for additional convenience.
