### ISSUE TITLE
Run rustc's test suite

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#74]
To help figure out what in Rust is and isn't supported using the `rust-gpu` backend we should try to see if it's feasible to test running rustc's test suite, or at least forking the current set of tests and adapting those to be testable with `rust-gpu`.

**Comment by khyperia** [comment]
Is this still something we want to do? I'm not sure if it's actually very useful or not, and it'd probably be better to flesh out our own compiletests with our stuff

**Comment by XAMPPRocky** [comment]
>  I'm not sure if it's actually very useful or not, and it'd probably be better to flesh out our own compiletests with our stuff

Well I did mean more, essentially trying to copy tests from rustc into our compiletest and saving the ones that fail. But this is more of something I should just do, and then open issues with the specific code samples and errors.
