### ISSUE TITLE
Ray Query intersection types

### ISSUE THREAD

**Issue by msiglreith** [EmbarkStudios/rust-gpu#745]
`RayQuery::get_intersection_type` and friends take const generic. Would be nice to expose these as enum similar to `Scope` for example. 
```rust
enum RayQueryIntersection {
   Candidate = 0,
   Committed = 1,
}
```

The other part would be the return value, which depends on the used intersection type. I'm not sure how to expose these properly, beside maybe specialize the `get_intersection_type` and use newtypes or just keep the `u32` and just expose `RayQueryCommittedIntersectionNoneKHR`, etc as consts

Specification: https://github.com/KhronosGroup/SPIRV-Registry/blob/main/extensions/KHR/SPV_KHR_ray_query.asciidoc

**Comment by khyperia** [comment]
Looking into this, I don't see any use case for using the const generics version - seems like just writing out two methods for every `<const INTERSECTION>` is the way to go. Docs and whatnot can be vastly improved that way, too.

I might be missing something, though, feel free to point something out.

**Comment by msiglreith** [comment]
Sure, that's fine for me! HLSL also went with the two method approach (https://microsoft.github.io/DirectX-Specs/d3d/Raytracing.html#rayquery)
