### ISSUE TITLE
`u32` inputs to a fragment shader that aren't decorated with `#[spirv(flat)]` are silently broken

### ISSUE THREAD

**Issue by expenses** [EmbarkStudios/rust-gpu#797]
Tbh this is more of a 'utgh why doesn't `spirv-val` catch this' type of error.

If you have a fragment shader that takes a `u32` from the vertex that isn't decorated with `#[spirv(flat)]` like this:

```rust
#[spirv(fragment)]
pub fn fragment(
    position: Vec3,
    normal: Vec3,
    uv: Vec2,
    material: u32,
    ...
```

It seems to be just read in the shader as `0` (on my gpu), but no warnings are given out at all. This most likely happens for all non-interpolatable attributes. Maybe 'GPU-Assisted; shader validation validation raises something, but that's not supported (on my gpu) for mixed stage shader modules.

`glslc` raises an error for this:

```glsl
#version 450

layout(location = 0) in uint i;
layout(location = 0) out vec4 o;

void main() {
    o = vec4(float(i));
}
```

```
.\x.frag:3: error: 'uint' : must be qualified as flat in
1 error generated.
```

Which is possibly why there's no validation error for this.

**Comment by AidanConnelly** [comment]
I've ran into this twice, and it's a real head-hurter trying to figure it out, so even though this isn't a problem with `rust-gpu` (and so not necessarily a bug), but rather vulkan/spirv, I feel the `rust`y way forward would be to make this issue more explicit.

**Comment by khyperia** [comment]
Some context from the spec:

Vulkan spec, section "9.19. Interpolation Decorations", in a heap of paragraphs, says:

> Fragment shader inputs that are signed or unsigned integers, integer vectors, or any double-precision floating-point type **must** be decorated with Flat.

The SPIR-V spec has no mention of the requirement, as far as I know.

So, it's a bug in spirv-val in that there should be a validation rule under `--target-env vulkan1.x` that validates this rule (spirv-val implements other vulkan-specific validation rules under the vulkan env flag). I'll file an issue. But yeah, we should probably also add a check to rust-gpu too - although we should check if e.g. the opengl spec has a similar rule if we make it a universal check rather than a check only enabled when compiling for vulkan.

**Comment by khyperia** [comment]
> we should check if e.g. the opengl spec has a similar rule

from [here](https://www.khronos.org/registry/OpenGL/specs/gl/glspec46.core.pdf)

> 13.7.1 Clipping Shader Outputs
> Implementations need not support interpolation of output values of integer or unsigned integer type, as all such attributes must be flat shaded.

However, there's also a changelog
> Changes in the released Specification update of October 30, 2014
> Modify the end of section 13.7.1 to remove language requiring that integer outputs be qualified as flat, since fragment shader inputs now control as described in the OpenGL Shading Language Specification (Bug 12623).

which uuuuh, seems pretty contradictory to me.

However, in the [GLSLang spec](https://www.khronos.org/registry/OpenGL/specs/gl/GLSLangSpec.4.60.pdf)

> 4.3.4. Input Variables
> Fragment shader inputs that are, or contain, integral or double-precision floating-point types must
be qualified with the interpolation qualifier flat.

(but that's the GLSL spec, not SPIR-V)

so uh, idklmao, seems like opengl probably disallows it too, but shruug
