### ISSUE TITLE
Intercept calls to (rust) libm and emit a builtin instead of the soft impl

### ISSUE THREAD

**Issue by khyperia** [EmbarkStudios/rust-gpu#81]
Plan is to go with @bjorn3's comment below and expose the GLOps not in std::intrinsics via intercepting calls to https://github.com/rust-lang/libm, which is used in e.g. `glam`'s `no_std` implementation.

Old title: Expose GLOps not in std::intrinsics

https://docs.rs/spirv_headers/1.5.0/spirv_headers/enum.GLOp.html , same with CLOp.

For example, `acos`.

**Comment by repi** [comment]
Ran into this today with `tan` that glam is using (#134), it is not part of the Rust core intrinsics functions. Any idea of how to add our own intrinsics, do we have to do that in core or as another set of intrinsics for the specific target?

**Comment by bjorn3** [comment]
libstd directly calls the libm functions. Adding an extra intrinsic requires a rustc change to add it to the list of intrinsics of typeck.

**Comment by repi** [comment]
Suspected that, definitely don't want to use `libm` on the GPU for where there is real GPU/SPIRV intrinsics to use

**Comment by bjorn3** [comment]
It should be possible to intercept calls to functions with specific names and instead emit a SPIRV instruction.

**Comment by khyperia** [comment]
Fixed by https://github.com/EmbarkStudios/rust-gpu/pull/264
