### ISSUE TITLE
`Image::read`/`Image::write` should allow reading/writing single scalars

### ISSUE THREAD

**Issue by expenses** [EmbarkStudios/rust-gpu#823]
This is something I just ran into. [OpImageRead](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpImageRead) for example only lets you read vectors, which isn't what you want if you have e.g. a `R8_UNORM` texture. Should be an easy fix.

**Comment by khyperia** [comment]
We'd like to match other shading languages here, for ease of transition, expectations, etc. - and other shading languages always return vec4, regardless of format. So, we'd like to keep it how it is.

**Comment by expenses** [comment]
Couldn't there just be additional read_scalar/write_scalar functions? You can already read vec2s/vec3s as well as vec4s with the current functions. It just feels super awkward to read a vec2 if you know you have a single channel image.
