### ISSUE TITLE
DCE shouldn't remove unused descriptors

### ISSUE THREAD

**Issue by expenses** [EmbarkStudios/rust-gpu#827]
I'm performing reflection on generated SPIR-V modules to create descriptor set layouts. Unfortunately, this is a little fiddly, because whenever I comment out some code to debug something, if it means that a descriptor is no longer used, this descriptor will not be output in the final module and the generated descriptor set layouts will be wrong.

In my opinion, this sort of Dead Code Elimination should not be performed, especially with `SpirvMetadata::NameVariables` or `NameVariables::Full`. Given that `SpirvMetadata::NameVariables` has the comment 'Only include OpNames for public interface variables (uniforms and the like), to allow shader reflection.', I think we can say that this DCE is unwanted behaviour.

**Comment by khyperia** [comment]
We already looked into this quite a bit in https://github.com/EmbarkStudios/rust-gpu/issues/722, and tl;dr, we cannot fix this for SPIR-V versions <=1.3. Use >=1.4 if keeping unused entry parameters is needed.

**Comment by expenses** [comment]
Oh, nice! That should probably be documented somewhere.

**Comment by expenses** [comment]
Actually the DCE still seems to happen even when building for `spirv-unknown-spv1.5`, at least on https://github.com/EmbarkStudios/rust-gpu/commit/da7c3ed71f27d67e05c0d2a4d3c839db14daf1f8.

**Comment by khyperia** [comment]
Ah, that would be a `spirv-opt` issue then, it's removing it - this doesn't include `samp`, but removing the `spirv-opt` invocation makes it appear: https://shader-playground.timjones.io/05a24c0565ef5fd9b8dc51457c8ad135

**Comment by expenses** [comment]
Ah, right! Looks like `spirv_tools::opt::Options::preserve_bindings` should be set to true then.
