### ISSUE TITLE
stop relying on spirv-tools

### ISSUE THREAD

**Issue by dvc94ch** [EmbarkStudios/rust-gpu#841]
currently the spirv spec says that subgroups are restricted to kernels. however glsl supports subgroups in regular compute shaders. seems like the glsl spec team forgot to tell the spirv spec team to update their specs. this leads to spirv-tools complaining about an invalid decorator in the opt/validation phases which in turn leads to rust-gpu not being competitive with glsl for no real reason. removing the dependency on spirv-tools would allow supporting "defacto" standards instead of just what was bothered to be written down in a spec.

- [0] https://github.com/KhronosGroup/GLSL/blob/master/extensions/khr/GL_KHR_shader_subgroup.txt

**Comment by khyperia** [comment]
> currently the spirv spec says that subgroups are restricted to kernels

can you show where it says that? not seeing where it says that.

**Comment by dvc94ch** [comment]
section 3.21 builtin says that kernel, groupnonuniform and sugroupballotkhr are enabling capabilities for `subgroup_size`, `num_subgroups`, `subgroup_id`, `subgroup_local_invocation_id`, to my understanding implying that they aren't available in the `GLCompute` mode, the `Kernel` mode being something to do with opencl.

**Comment by khyperia** [comment]
That's an `or` between each capability, not an `and` - you don't need `Kernel` to use `SubgroupSize` and friends, just `GroupNonUniform`. They're available in compute shader SPIR-V and rust-gpu, and pass spirv-val.

**Comment by dvc94ch** [comment]
so how do I enable it? I currently get this:

```
error: Operand 3 of Decorate requires one of these capabilities: Kernel GroupNonUniform SubgroupBallotKHR 
         OpDecorate %subgroup_local_invocation_id BuiltIn SubgroupLocalInvocationId
  |
  = note: module `/home/dvc/cloudpeer/xuda/target/shader/target/spirv-unknown-vulkan1.2/release/deps/shader.spv.dir/module`

warning: an unknown error occurred
  |
  = note: spirv-opt failed, leaving as unoptimized
  = note: module `/home/dvc/cloudpeer/xuda/target/shader/target/spirv-unknown-vulkan1.2/release/deps/shader.spv.dir/module`

error: error:0:0 - Operand 3 of Decorate requires one of these capabilities: Kernel GroupNonUniform SubgroupBallotKHR 
         OpDecorate %subgroup_local_invocation_id BuiltIn SubgroupLocalInvocationId
  |
  = note: spirv-val failed
  = note: module `/home/dvc/cloudpeer/xuda/target/shader/target/spirv-unknown-vulkan1.2/release/deps/shader.spv.dir/module`

warning: `shader` (lib) generated 1 warning
error: could not compile `shader` due to 2 previous errors; 1 warning emitted
```

**Comment by khyperia** [comment]
As the error implies, you need to enable "**one** of these capabilities: Kernel GroupNonUniform SubgroupBallotKHR". You can do that using the [API to enable capabilities](https://embarkstudios.github.io/rust-gpu/api/spirv_builder/struct.SpirvBuilder.html#method.capability).
