### ISSUE TITLE
CI tests fails with latest spirv-val

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-gpu#865]
The Mac builds in CI use latest available `spirv-val` and that started failing the tests now. Possibly from the [SPIRV-Tools v2022.2 release](https://github.com/KhronosGroup/SPIRV-Tools/releases/tag/v2022.2) 10 days ago

https://github.com/EmbarkStudios/rust-gpu/runs/6053175509?check_suite_focus=true

```
test [ui] ui/image/sample_depth_reference/sample_gradient.rs ... FAILED
normalized stderr:
error: error:0:0 - [VUID-StandaloneSpirv-OpImage-04777] In Vulkan, OpImage*Dref* instructions must not use images with a 3D Dim
  |
  = note: spirv-val failed
  = note: module `$TEST_BUILD_DIR/image/sample_depth_reference/sample_lod.stage-id.spv.dir/module`

error: aborting due to previous error
```

Linux and Windows tests do not fail as they use a fixed frozen spirv-val version that it downloads, though we should upgrade that also. Filed:
- #866

**Comment by eddyb** [comment]
Fixed in the commit I added to #867 (see https://github.com/EmbarkStudios/rust-gpu/pull/867#pullrequestreview-945526022).
