### ISSUE TITLE
Upgrade CI to use latest prebuilt spirv-tools on Windows & Linux

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-gpu#866]
We currently use a very old version from 2021-08-05 which doesn't fail our tests, but latest does (#865). So need to upgrade our CI to use latest available pre-built spirv-tools.

But can't find any instructions of where to find these magic pre-built URLs and a google search doesn't reveal it either. These URLs:

> https://storage.googleapis.com/spirv-tools/artifacts/prod/graphics_shader_compiler/spirv-tools/linux-clang-release/continuous/1530/20210805-040049

@Jake-Shadle do you remember what site  #162 found what the latest prebuilds are? Ideally we shouldn't be using specific dates/commits either but stable versioned spirv-tools releases instead. Unfortunate that SPIRV-Tools repo still doesn't have any official prebuilds.

**Comment by Jake-Shadle** [comment]
They're from this [page](https://github.com/KhronosGroup/SPIRV-Tools/blob/master/docs/downloads.md), they're just the direct CI artifacts, which is terrible, but... :shrug:

**Comment by repi** [comment]
Thanks, will test to upgrade to it and add link in the CI definitions to the page for next time

**Comment by eddyb** [comment]
Should we try to keep `spirv-tools-rs` in sync? For example, I couldn't reproduce the validation failures when using the version compiled through `spirv-tools-rs`.

**Comment by repi** [comment]
Think we should, but `spirv-tools-rs` also is on a frozen fork of SPRIV-Tools that we need to update also. 

@Jake-Shadle could you do that?

**Comment by Jake-Shadle** [comment]
Sure.
