### ISSUE TITLE
Inefficient loop structurization (unnecessarily converts `do`-`while` to `while`).

### ISSUE THREAD

**Issue by eddyb** [EmbarkStudios/rust-gpu#872]
There's this comment I left in the structurizer (and the `do`-`while`->`while` conversion that follows it): https://github.com/EmbarkStudios/rust-gpu/blob/03f89e8ba6f236218b3c5f9b18fe03c25a4d6a5c/crates/rustc_codegen_spirv/src/linker/structurizer.rs#L307-L310

Which seemed reasonable until I realized that `do`-`while` makes more sense for structured control-flow, and SPIR-V special-cases `while`-like CFGs to even allow them, e.g. [RVSDG only has `do`-`while` (called *`θ`*/"theta")](https://arxiv.org/pdf/1912.05036.pdf#page=8).

And another look at [`OpLoopMerge`'s docs](https://www.khronos.org/registry/SPIR-V/specs/unified1/SPIRV.html#OpLoopMerge) does confirm it can be applied to an unconditional `OpBranch`, and combined with conditional breaks out of loops (which SPIR-V also supports), that implies `do`-`while` is possible.

As another data point, I looked at [what glslang outputs for a simple `do`-`while` loop](https://shader-playground.timjones.io/cf0ebe5f026dad124c45094ffb906b0e):
```llvm
               OpBranch %6

          %6 = OpLabel ; loop header
               OpLoopMerge %8 %9 None
               OpBranch %7

          %7 = OpLabel ; loop body
         ; ...
               OpBranch %9

          %9 = OpLabel ; loop condition / "continue" merge
         ; ...
               OpBranchConditional ... %6 %8

          %8 = OpLabel ; loop exit / "break" merge
```

So that definitely is the kind of `do`-`while`-like CFG shape I would've wanted to use when I wrote the structurizer, but I must've assumed the wrong limitation without double-checking.

Cleaning this up should be possible, but I'm not sure what edge cases have to be taken into account (e.g. the whole idea of a "continue" merge is useful for emitting SPIR-V from GLSL, but gets in the way of structured reasoning).

It might be possible that roundtripping through SPIR-T's structured encoding of control-flow will end up replacing the existing structurizer before we get to do any more cleanups like this.

**Comment by repi** [comment]
this is still a GPU performance problem, @VZout has a good example of a conversion to while loop instead of for loop for our depth-of-field shader with major speedup as result.

internal PR for that which is a good example:
- https://github.com/EmbarkStudios/ark/pull/7677

**Comment by eddyb** [comment]
To be clear this affects *all* loops equally, whereas `for` loops may have further issues, like the `mouse-shader` example is currently broken because `naga` silently miscompiles the SPIR-V for the `for` loop (and changing it to a `while` loop unbreaks it).

**Comment by eddyb** [comment]
SPIR-T's structurizer always does `do`-`while` directly (i.e. it only has "tail-controlled loops"), and:
* #1052

just landed, so this is no longer relevant.
