### ISSUE TITLE
Release versioned rust-gpu crates

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-gpu#881]
So users don't have to depend on them as a git dependency.

We can still publish quite frequently and do breaking changes as it is pre 1.0 semver

**Comment by koopa1338** [comment]
How is the status of release current version tags on crates.io? Relying on the git repositories is pretty inconvenient even just for testing...

**Comment by repi** [comment]
@oisyn should do it soon but no exact time set

**Comment by oisyn** [comment]
Hi @koopa1338, all public facing crates and their dependencies were published to crates.io yesterday under version `0.4.0-alpha.13`

Today I'll be publishing `0.4.0-alpha.14` which mainly contains a rename of the crate `spirv-types` to `spirv-std-types`, but it's unlikely a project making use of rust-gpu references that crate directly so you probably shouldn't be worried about it, but still a heads-up :)
