### ISSUE TITLE
Don't use `OpKill` instead use `OpTerminateInvocation` or `OpDemoteToHelperInvocation`

### ISSUE THREAD

**Issue by VZout** [EmbarkStudios/rust-gpu#884]
According to spir-v spec `OpKill` is deprecated and recommends to us `OpTerminateInvocation` or `OpDemoteToHelperInvocation` instead. We probably should then also deprecate it in spirv-std.

**Comment by hrydgard** [comment]
I don't think this is applicable until we are using SPIR-V 1.6, which we won't for the foreseeable future.

**Comment by VZout** [comment]
Jup your right
