### ISSUE TITLE
Integration with vulkano.rs - Missing name for input vertex buffer variable

### ISSUE THREAD

**Issue by portaloffreedom** [EmbarkStudios/rust-gpu#887]
### Expected Behaviour

Loading a vertex shader made with rust-gpu using vulkano.rs should work.

### Example & Steps To Reproduce

1. Create a vertex shader that has input buffers (vertex buffer) (what is the official name? I don't remember)
```rust
#[spirv(vertex)]
pub fn main_vs(
    position: Vec2,
    #[spirv(position, invariant)] out_pos: &mut Vec4,
) {
    *out_pos = vec4(
        position.x,
        position.y,
        0.0,
        1.0,
    );
}
```
2. Load the shader in vulkano
3. Create and build a pipeline

At the moment of creating the pipeline, vulkano tries to look for the vertex buffer binding in the shader, and it fails because it could not load a "Instruction::name" when introspecting the shader.
```rust
let name = id_info
    .iter_name()
    .find_map(|instruction| match instruction {
        Instruction::Name { name, .. } => Some(Cow::Owned(name.to_owned())),
        _ => None,
    });
```
vulkano code from here: https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/shader/reflect.rs#L1020-L1025
                
The code doesn't crash immediately, but sets the "name" to None, and unwraps it later causing vulkano to crash.

Seems to me rust-gpu could add a name instructions for input buffers? I could be totally wrong. I'm happy to open a bug report on vulkano if you believe they are doing something wrong, just thought of starting here first.

An example repo showing the bug is here: https://github.com/portaloffreedom/rustgpu-test/tree/rust-gpu

## System Info

replicated on two different (similar) systems
 - Rust: nightly-2022-04-11-x86_64-unknown-linux-gnu
 - OS: archlinux / opensuse tumbleweed
 - GPU: Radeon 5700 xt  / Radeon vega 8 integrated graphics
 - SPIR-V: not sure how to extract this info

## Backtrace

Not very relevant, as the error happens before, when the name variable is not found and therefore not set.
<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/matteo/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.29.0/src/pipeline/graphics/vertex_input/buffers.rs:112:46
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/core/src/option.rs:755:21
   4: <vulkano::pipeline::graphics::vertex_input::buffers::BuffersDefinition as vulkano::pipeline::graphics::vertex_input::definition::VertexDefinition>::definition
             at /home/matteo/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.29.0/src/pipeline/graphics/vertex_input/buffers.rs:112:24
   5: vulkano::pipeline::graphics::builder::GraphicsPipelineBuilder<Vdef,Vss,Tcss,Tess,Gss,Fss>::with_pipeline_layout
             at /home/matteo/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.29.0/src/pipeline/graphics/builder.rs:253:39
   6: vulkano::pipeline::graphics::builder::GraphicsPipelineBuilder<Vdef,Vss,Tcss,Tess,Gss,Fss>::with_auto_layout
             at /home/matteo/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.29.0/src/pipeline/graphics/builder.rs:236:9
   7: vulkano::pipeline::graphics::builder::GraphicsPipelineBuilder<Vdef,Vss,Tcss,Tess,Gss,Fss>::build
             at /home/matteo/.cargo/registry/src/github.com-1ecc6299db9ec823/vulkano-0.29.0/src/pipeline/graphics/builder.rs:134:9
   8: rustgpu_app::simple_graphics::simple_graphics
             at ./app/src/simple_graphics.rs:133:20
   9: rustgpu_app::main
             at ./app/src/main.rs:43:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/1f7fb6413d6d6c0c929b223e478e44c3db991b03/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by msiglreith** [comment]
By default rust-gpu (or spirv-opt later on) strips all non relevant information from spirv module iirc. Enabling metadata in the spirv builder should keep the interface names at least which vulkano probavbly uses the lookup the location information of the vertex attribute https://github.com/EmbarkStudios/rust-gpu/blob/0866cf591a7fdbbd15bdb3468e192bb9b6189fd0/crates/spirv-builder/src/lib.rs#L230

**Comment by portaloffreedom** [comment]
Thanks!
Adding `.spirv_metadata(SpirvMetadata::NameVariables)` solves it and now it works :)
Type to start some serious shader programming :D
