### ISSUE TITLE
Make sure the docs.rs build of `spirv-builder` doesn't build `rustc_codegen_spirv`

### ISSUE THREAD

**Issue by oisyn** [EmbarkStudios/rust-gpu#970]
Currently, the docs.rs build for `spirv-builder` fails: https://docs.rs/crate/spirv-builder/0.4.0-alpha.17/builds/667359. This is because docs.rs builds using their nightly version, which is incompatible with `rustc_codegen_spirv`.

We can't do much for `rustc_codegen_spirv` (besides stripping code for doc builds), but we can remove `spirv-builder`'s dependency on `rustc_codegen_spirv` specifically for doc.rs builds to make it succeed.

**Comment by eddyb** [comment]
Fixed in `0.9.0` (https://docs.rs/spirv-builder/0.9.0), by:
- #1079
