### ISSUE TITLE
Incorrect spirv instruction `OpAtomicFMaxEXT` used in `atomic_f_add`

### ISSUE THREAD

**Issue by apriori** [EmbarkStudios/rust-gpu#994]
https://github.com/EmbarkStudios/rust-gpu/blob/e4a41cda19548b04749c9773ca703fbb4623f980/crates/spirv-std/src/arch/atomics.rs#L590-L601

**Comment by LegNeato** [comment]
Should that be `OpAtomicFAddEXT`?

**Comment by apriori** [comment]
Yes, it should. This seems to be a copy-and-paste error from a prior function definition.
